// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "data.core.proto" (package "fibertest30.data.core", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { MeasurementSettings } from "./data.otdr";
import { Duration } from "./google/protobuf/duration";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message fibertest30.data.core.SystemEventSource
 */
export interface SystemEventSource {
    /**
     * @generated from protobuf field: string userId = 1;
     */
    userId: string;
    /**
     * @generated from protobuf field: string source = 2;
     */
    source: string;
}
/**
 * @generated from protobuf message fibertest30.data.core.SystemEvent
 */
export interface SystemEvent {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string type = 2;
     */
    type: string;
    /**
     * @generated from protobuf field: fibertest30.data.core.SystemEventLevel level = 3;
     */
    level: SystemEventLevel;
    /**
     * @generated from protobuf field: fibertest30.data.core.SystemEventSource source = 4;
     */
    source?: SystemEventSource;
    /**
     * @generated from protobuf field: string jsonData = 5;
     */
    jsonData: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp at = 6;
     */
    at?: Timestamp;
}
/**
 * @generated from protobuf message fibertest30.data.core.MonitoringSchedule
 */
export interface MonitoringSchedule {
    /**
     * @generated from protobuf field: fibertest30.data.core.MonitoringSchedulerMode schedulerMode = 1;
     */
    schedulerMode: MonitoringSchedulerMode;
    /**
     * @generated from protobuf field: google.protobuf.Duration interval = 2;
     */
    interval?: Duration;
    /**
     * @generated from protobuf field: repeated int32 timeSlotIds = 3;
     */
    timeSlotIds: number[];
}
/**
 * @generated from protobuf message fibertest30.data.core.MonitoringBaseline
 */
export interface MonitoringBaseline {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: int32 monitoringPortId = 2;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: string createdByUserId = 3;
     */
    createdByUserId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp createdAt = 4;
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: fibertest30.data.otdr.MeasurementSettings measurementSettings = 5;
     */
    measurementSettings?: MeasurementSettings;
}
/**
 * @generated from protobuf message fibertest30.data.core.MonitoringPort
 */
export interface MonitoringPort {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: int32 otauPortId = 2;
     */
    otauPortId: number;
    /**
     * @generated from protobuf field: int32 otauId = 3;
     */
    otauId: number;
    /**
     * @generated from protobuf field: fibertest30.data.core.MonitoringPortStatus status = 4;
     */
    status: MonitoringPortStatus;
    /**
     * @generated from protobuf field: fibertest30.data.core.MonitoringSchedulerMode schedulerMode = 5;
     */
    schedulerMode: MonitoringSchedulerMode;
    /**
     * @generated from protobuf field: fibertest30.data.core.MonitoringBaseline baseline = 6;
     */
    baseline?: MonitoringBaseline;
    /**
     * @generated from protobuf field: google.protobuf.Duration interval = 7;
     */
    interval?: Duration;
    /**
     * @generated from protobuf field: repeated int32 timeSlotIds = 8;
     */
    timeSlotIds: number[];
    /**
     * @generated from protobuf field: int32 alarmProfileId = 9;
     */
    alarmProfileId: number;
    /**
     * @generated from protobuf field: string Note = 10 [json_name = "Note"];
     */
    note: string;
}
/**
 * @generated from protobuf message fibertest30.data.core.TimeOnlyHourMinute
 */
export interface TimeOnlyHourMinute {
    /**
     * @generated from protobuf field: int32 hour = 1;
     */
    hour: number;
    /**
     * @generated from protobuf field: int32 minute = 2;
     */
    minute: number;
}
/**
 * @generated from protobuf message fibertest30.data.core.MonitoringTimeSlot
 */
export interface MonitoringTimeSlot {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: fibertest30.data.core.TimeOnlyHourMinute start = 2;
     */
    start?: TimeOnlyHourMinute;
    /**
     * @generated from protobuf field: fibertest30.data.core.TimeOnlyHourMinute end = 3;
     */
    end?: TimeOnlyHourMinute;
}
/**
 * @generated from protobuf message fibertest30.data.core.Threshold
 */
export interface Threshold {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: fibertest30.data.core.ThresholdParameter parameter = 2;
     */
    parameter: ThresholdParameter;
    /**
     * @generated from protobuf field: bool isMinorOn = 3;
     */
    isMinorOn: boolean;
    /**
     * @generated from protobuf field: optional double minor = 4;
     */
    minor?: number;
    /**
     * @generated from protobuf field: bool isMajorOn = 5;
     */
    isMajorOn: boolean;
    /**
     * @generated from protobuf field: optional double major = 6;
     */
    major?: number;
    /**
     * @generated from protobuf field: bool isCriticalOn = 7;
     */
    isCriticalOn: boolean;
    /**
     * @generated from protobuf field: optional double critical = 8;
     */
    critical?: number;
}
/**
 * @generated from protobuf message fibertest30.data.core.AlarmProfile
 */
export interface AlarmProfile {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: repeated fibertest30.data.core.Threshold thresholds = 3;
     */
    thresholds: Threshold[];
}
/**
 * @generated from protobuf message fibertest30.data.core.EmailServer
 */
export interface EmailServer {
    /**
     * @generated from protobuf field: bool enabled = 1;
     */
    enabled: boolean;
    /**
     * @generated from protobuf field: string serverAddress = 2;
     */
    serverAddress: string;
    /**
     * @generated from protobuf field: int32 serverPort = 3;
     */
    serverPort: number;
    /**
     * @generated from protobuf field: string outgoingAddress = 4;
     */
    outgoingAddress: string;
    /**
     * @generated from protobuf field: string serverUserName = 5;
     */
    serverUserName: string;
    /**
     * @generated from protobuf field: string serverPassword = 6;
     */
    serverPassword: string;
    /**
     * @generated from protobuf field: bool verifyCertificate = 7;
     */
    verifyCertificate: boolean;
    /**
     * @generated from protobuf field: bool floodingPolicy = 8;
     */
    floodingPolicy: boolean;
    /**
     * @generated from protobuf field: bool smsOverSmtp = 9;
     */
    smsOverSmtp: boolean;
    /**
     * @generated from protobuf field: bool isPasswordSet = 10;
     */
    isPasswordSet: boolean;
    /**
     * @generated from protobuf field: bool isAuthenticationOn = 11;
     */
    isAuthenticationOn: boolean;
}
/**
 * @generated from protobuf message fibertest30.data.core.TrapReceiver
 */
export interface TrapReceiver {
    /**
     * @generated from protobuf field: bool enabled = 1;
     */
    enabled: boolean;
    /**
     * @generated from protobuf field: string snmpVersion = 2;
     */
    snmpVersion: string;
    /**
     * @generated from protobuf field: bool useVeexOid = 3;
     */
    useVeexOid: boolean;
    /**
     * @generated from protobuf field: string customOid = 4;
     */
    customOid: string;
    /**
     * @generated from protobuf field: string community = 5;
     */
    community: string;
    /**
     * @generated from protobuf field: string AuthoritativeEngineId = 6 [json_name = "AuthoritativeEngineId"];
     */
    authoritativeEngineId: string;
    /**
     * @generated from protobuf field: string UserName = 7 [json_name = "UserName"];
     */
    userName: string;
    /**
     * @generated from protobuf field: string AuthenticationPassword = 8 [json_name = "AuthenticationPassword"];
     */
    authenticationPassword: string;
    /**
     * @generated from protobuf field: string AuthenticationProtocol = 9 [json_name = "AuthenticationProtocol"];
     */
    authenticationProtocol: string;
    /**
     * @generated from protobuf field: string PrivacyPassword = 10 [json_name = "PrivacyPassword"];
     */
    privacyPassword: string;
    /**
     * @generated from protobuf field: string PrivacyProtocol = 11 [json_name = "PrivacyProtocol"];
     */
    privacyProtocol: string;
    /**
     * @generated from protobuf field: string TrapReceiverAddress = 12 [json_name = "TrapReceiverAddress"];
     */
    trapReceiverAddress: string;
    /**
     * @generated from protobuf field: int32 TrapReceiverPort = 13 [json_name = "TrapReceiverPort"];
     */
    trapReceiverPort: number;
    /**
     * @generated from protobuf field: bool isAuthPwdSet = 14;
     */
    isAuthPwdSet: boolean;
    /**
     * @generated from protobuf field: bool isPrivPwdSet = 15;
     */
    isPrivPwdSet: boolean;
}
/**
 * @generated from protobuf message fibertest30.data.core.NotificationSettings
 */
export interface NotificationSettings {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: fibertest30.data.core.EmailServer emailServer = 2;
     */
    emailServer?: EmailServer;
    /**
     * @generated from protobuf field: fibertest30.data.core.TrapReceiver trapReceiver = 3;
     */
    trapReceiver?: TrapReceiver;
}
/**
 * @generated from protobuf message fibertest30.data.core.NetworkSettings
 */
export interface NetworkSettings {
    /**
     * @generated from protobuf field: string networkMode = 1;
     */
    networkMode: string;
    /**
     * @generated from protobuf field: string localIpAddress = 2;
     */
    localIpAddress: string;
    /**
     * @generated from protobuf field: string localSubnetMask = 3;
     */
    localSubnetMask: string;
    /**
     * @generated from protobuf field: string localGatewayIp = 4;
     */
    localGatewayIp: string;
    /**
     * @generated from protobuf field: optional string primaryDnsServer = 5;
     */
    primaryDnsServer?: string;
    /**
     * @generated from protobuf field: optional string secondaryDnsServer = 6;
     */
    secondaryDnsServer?: string;
}
/**
 * @generated from protobuf message fibertest30.data.core.AppTimeZone
 */
export interface AppTimeZone {
    /**
     * @generated from protobuf field: string ianaId = 1;
     */
    ianaId: string;
    /**
     * @generated from protobuf field: string displayName = 2;
     */
    displayName: string;
    /**
     * @generated from protobuf field: string displayBaseUtcOffset = 3;
     */
    displayBaseUtcOffset: string;
}
/**
 * @generated from protobuf message fibertest30.data.core.NtpSettings
 */
export interface NtpSettings {
    /**
     * @generated from protobuf field: optional string primaryNtpServer = 1;
     */
    primaryNtpServer?: string;
    /**
     * @generated from protobuf field: optional string secondaryNtpServer = 2;
     */
    secondaryNtpServer?: string;
}
/**
 * @generated from protobuf message fibertest30.data.core.TimeSettings
 */
export interface TimeSettings {
    /**
     * @generated from protobuf field: fibertest30.data.core.AppTimeZone appTimeZone = 1;
     */
    appTimeZone?: AppTimeZone;
    /**
     * @generated from protobuf field: fibertest30.data.core.NtpSettings ntpSettings = 2;
     */
    ntpSettings?: NtpSettings;
}
/**
 * @generated from protobuf enum fibertest30.data.core.SystemEventLevel
 */
export enum SystemEventLevel {
    /**
     * @generated from protobuf enum value: Internal = 0;
     */
    Internal = 0,
    /**
     * @generated from protobuf enum value: Info = 1;
     */
    Info = 1,
    /**
     * @generated from protobuf enum value: Major = 2;
     */
    Major = 2,
    /**
     * @generated from protobuf enum value: Critical = 3;
     */
    Critical = 3
}
/**
 * @generated from protobuf enum fibertest30.data.core.MonitoringPortStatus
 */
export enum MonitoringPortStatus {
    /**
     * @generated from protobuf enum value: Off = 0;
     */
    Off = 0,
    /**
     * @generated from protobuf enum value: On = 1;
     */
    On = 1,
    /**
     * @generated from protobuf enum value: Maintenance = 2;
     */
    Maintenance = 2
}
/**
 * @generated from protobuf enum fibertest30.data.core.MonitoringSchedulerMode
 */
export enum MonitoringSchedulerMode {
    /**
     * @generated from protobuf enum value: RoundRobin = 0;
     */
    RoundRobin = 0,
    /**
     * @generated from protobuf enum value: FixedTimeSlot = 1;
     */
    FixedTimeSlot = 1,
    /**
     * @generated from protobuf enum value: AtLeastOnceIn = 2;
     */
    AtLeastOnceIn = 2
}
/**
 * @generated from protobuf enum fibertest30.data.core.ThresholdParameter
 */
export enum ThresholdParameter {
    /**
     * @generated from protobuf enum value: EventLoss = 0;
     */
    EventLoss = 0,
    /**
     * @generated from protobuf enum value: TotalLoss = 1;
     */
    TotalLoss = 1,
    /**
     * @generated from protobuf enum value: EventReflectance = 2;
     */
    EventReflectance = 2,
    /**
     * @generated from protobuf enum value: SectionAttenuation = 3;
     */
    SectionAttenuation = 3,
    /**
     * @generated from protobuf enum value: SectionLoss = 4;
     */
    SectionLoss = 4,
    /**
     * @generated from protobuf enum value: SectionLengthChange = 5;
     */
    SectionLengthChange = 5,
    /**
     * @generated from protobuf enum value: PortHealth = 6;
     */
    PortHealth = 6
}
// @generated message type with reflection information, may provide speed optimized methods
class SystemEventSource$Type extends MessageType<SystemEventSource> {
    constructor() {
        super("fibertest30.data.core.SystemEventSource", [
            { no: 1, name: "userId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.SystemEventSource
 */
export const SystemEventSource = new SystemEventSource$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SystemEvent$Type extends MessageType<SystemEvent> {
    constructor() {
        super("fibertest30.data.core.SystemEvent", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "level", kind: "enum", T: () => ["fibertest30.data.core.SystemEventLevel", SystemEventLevel] },
            { no: 4, name: "source", kind: "message", T: () => SystemEventSource },
            { no: 5, name: "jsonData", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "at", kind: "message", T: () => Timestamp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.SystemEvent
 */
export const SystemEvent = new SystemEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MonitoringSchedule$Type extends MessageType<MonitoringSchedule> {
    constructor() {
        super("fibertest30.data.core.MonitoringSchedule", [
            { no: 1, name: "schedulerMode", kind: "enum", T: () => ["fibertest30.data.core.MonitoringSchedulerMode", MonitoringSchedulerMode] },
            { no: 2, name: "interval", kind: "message", T: () => Duration },
            { no: 3, name: "timeSlotIds", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.MonitoringSchedule
 */
export const MonitoringSchedule = new MonitoringSchedule$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MonitoringBaseline$Type extends MessageType<MonitoringBaseline> {
    constructor() {
        super("fibertest30.data.core.MonitoringBaseline", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "createdByUserId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "createdAt", kind: "message", T: () => Timestamp },
            { no: 5, name: "measurementSettings", kind: "message", T: () => MeasurementSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.MonitoringBaseline
 */
export const MonitoringBaseline = new MonitoringBaseline$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MonitoringPort$Type extends MessageType<MonitoringPort> {
    constructor() {
        super("fibertest30.data.core.MonitoringPort", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "otauPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "otauId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "status", kind: "enum", T: () => ["fibertest30.data.core.MonitoringPortStatus", MonitoringPortStatus] },
            { no: 5, name: "schedulerMode", kind: "enum", T: () => ["fibertest30.data.core.MonitoringSchedulerMode", MonitoringSchedulerMode] },
            { no: 6, name: "baseline", kind: "message", T: () => MonitoringBaseline },
            { no: 7, name: "interval", kind: "message", T: () => Duration },
            { no: 8, name: "timeSlotIds", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "alarmProfileId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "Note", kind: "scalar", jsonName: "Note", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.MonitoringPort
 */
export const MonitoringPort = new MonitoringPort$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TimeOnlyHourMinute$Type extends MessageType<TimeOnlyHourMinute> {
    constructor() {
        super("fibertest30.data.core.TimeOnlyHourMinute", [
            { no: 1, name: "hour", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "minute", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.TimeOnlyHourMinute
 */
export const TimeOnlyHourMinute = new TimeOnlyHourMinute$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MonitoringTimeSlot$Type extends MessageType<MonitoringTimeSlot> {
    constructor() {
        super("fibertest30.data.core.MonitoringTimeSlot", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "start", kind: "message", T: () => TimeOnlyHourMinute },
            { no: 3, name: "end", kind: "message", T: () => TimeOnlyHourMinute }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.MonitoringTimeSlot
 */
export const MonitoringTimeSlot = new MonitoringTimeSlot$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Threshold$Type extends MessageType<Threshold> {
    constructor() {
        super("fibertest30.data.core.Threshold", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "parameter", kind: "enum", T: () => ["fibertest30.data.core.ThresholdParameter", ThresholdParameter] },
            { no: 3, name: "isMinorOn", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "minor", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "isMajorOn", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "major", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "isCriticalOn", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "critical", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.Threshold
 */
export const Threshold = new Threshold$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AlarmProfile$Type extends MessageType<AlarmProfile> {
    constructor() {
        super("fibertest30.data.core.AlarmProfile", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "thresholds", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Threshold }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.AlarmProfile
 */
export const AlarmProfile = new AlarmProfile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmailServer$Type extends MessageType<EmailServer> {
    constructor() {
        super("fibertest30.data.core.EmailServer", [
            { no: 1, name: "enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "serverAddress", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "serverPort", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "outgoingAddress", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "serverUserName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "serverPassword", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "verifyCertificate", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "floodingPolicy", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "smsOverSmtp", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "isPasswordSet", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 11, name: "isAuthenticationOn", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.EmailServer
 */
export const EmailServer = new EmailServer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TrapReceiver$Type extends MessageType<TrapReceiver> {
    constructor() {
        super("fibertest30.data.core.TrapReceiver", [
            { no: 1, name: "enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "snmpVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "useVeexOid", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "customOid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "community", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "AuthoritativeEngineId", kind: "scalar", jsonName: "AuthoritativeEngineId", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "UserName", kind: "scalar", jsonName: "UserName", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "AuthenticationPassword", kind: "scalar", jsonName: "AuthenticationPassword", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "AuthenticationProtocol", kind: "scalar", jsonName: "AuthenticationProtocol", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "PrivacyPassword", kind: "scalar", jsonName: "PrivacyPassword", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "PrivacyProtocol", kind: "scalar", jsonName: "PrivacyProtocol", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "TrapReceiverAddress", kind: "scalar", jsonName: "TrapReceiverAddress", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "TrapReceiverPort", kind: "scalar", jsonName: "TrapReceiverPort", T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "isAuthPwdSet", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 15, name: "isPrivPwdSet", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.TrapReceiver
 */
export const TrapReceiver = new TrapReceiver$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotificationSettings$Type extends MessageType<NotificationSettings> {
    constructor() {
        super("fibertest30.data.core.NotificationSettings", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "emailServer", kind: "message", T: () => EmailServer },
            { no: 3, name: "trapReceiver", kind: "message", T: () => TrapReceiver }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.NotificationSettings
 */
export const NotificationSettings = new NotificationSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NetworkSettings$Type extends MessageType<NetworkSettings> {
    constructor() {
        super("fibertest30.data.core.NetworkSettings", [
            { no: 1, name: "networkMode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "localIpAddress", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "localSubnetMask", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "localGatewayIp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "primaryDnsServer", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "secondaryDnsServer", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.NetworkSettings
 */
export const NetworkSettings = new NetworkSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AppTimeZone$Type extends MessageType<AppTimeZone> {
    constructor() {
        super("fibertest30.data.core.AppTimeZone", [
            { no: 1, name: "ianaId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "displayName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "displayBaseUtcOffset", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.AppTimeZone
 */
export const AppTimeZone = new AppTimeZone$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NtpSettings$Type extends MessageType<NtpSettings> {
    constructor() {
        super("fibertest30.data.core.NtpSettings", [
            { no: 1, name: "primaryNtpServer", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "secondaryNtpServer", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.NtpSettings
 */
export const NtpSettings = new NtpSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TimeSettings$Type extends MessageType<TimeSettings> {
    constructor() {
        super("fibertest30.data.core.TimeSettings", [
            { no: 1, name: "appTimeZone", kind: "message", T: () => AppTimeZone },
            { no: 2, name: "ntpSettings", kind: "message", T: () => NtpSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.data.core.TimeSettings
 */
export const TimeSettings = new TimeSettings$Type();
