// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "events.data.proto" (package "fibertest30.events.data", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { ChannelEvent } from "./ft.enums";
import { EventStatus } from "./ft.enums";
import { FiberState } from "./ft.enums";
import { BaseRefType } from "./ft.enums";
import { Duration } from "./google/protobuf/duration";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message fibertest30.events.data.DateTimeRange
 */
export interface DateTimeRange {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp start = 1;
     */
    start?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp end = 2;
     */
    end?: Timestamp;
}
/**
 * @generated from protobuf message fibertest30.events.data.DateTimeFilter
 */
export interface DateTimeFilter {
    /**
     * @generated from protobuf field: fibertest30.events.data.DateTimeRange searchWindow = 1;
     */
    searchWindow?: DateTimeRange;
    /**
     * @generated from protobuf field: google.protobuf.Duration relativeFromNow = 2;
     */
    relativeFromNow?: Duration;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp loadSince = 3;
     */
    loadSince?: Timestamp;
    /**
     * @generated from protobuf field: bool orderDescending = 4;
     */
    orderDescending: boolean;
}
/**
 * @generated from protobuf message fibertest30.events.data.OpticalEvent
 */
export interface OpticalEvent {
    /**
     * @generated from protobuf field: int32 eventId = 1;
     */
    eventId: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp measuredAt = 2;
     */
    measuredAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp registeredAt = 3;
     */
    registeredAt?: Timestamp;
    /**
     * @generated from protobuf field: string rtuTitle = 4;
     */
    rtuTitle: string;
    /**
     * @generated from protobuf field: string rtuId = 5;
     */
    rtuId: string;
    /**
     * @generated from protobuf field: string traceTitle = 6;
     */
    traceTitle: string;
    /**
     * @generated from protobuf field: string traceId = 7;
     */
    traceId: string;
    /**
     * @generated from protobuf field: fibertest30.ft.enums.BaseRefType baseRefType = 8;
     */
    baseRefType: BaseRefType;
    /**
     * @generated from protobuf field: fibertest30.ft.enums.FiberState traceState = 9;
     */
    traceState: FiberState;
    /**
     * @generated from protobuf field: fibertest30.ft.enums.EventStatus eventStatus = 10;
     */
    eventStatus: EventStatus;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp statusChangedAt = 11;
     */
    statusChangedAt?: Timestamp;
    /**
     * @generated from protobuf field: string statusChangedByUser = 12;
     */
    statusChangedByUser: string;
    /**
     * @generated from protobuf field: string comment = 13;
     */
    comment: string;
}
/**
 * @generated from protobuf message fibertest30.events.data.NetworkEvent
 */
export interface NetworkEvent {
    /**
     * @generated from protobuf field: int32 eventId = 1;
     */
    eventId: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp registeredAt = 2;
     */
    registeredAt?: Timestamp;
    /**
     * @generated from protobuf field: string rtuId = 3;
     */
    rtuId: string;
    /**
     * @generated from protobuf field: string rtuTitle = 4;
     */
    rtuTitle: string;
    /**
     * @generated from protobuf field: bool isRtuAvailable = 5;
     */
    isRtuAvailable: boolean;
    /**
     * @generated from protobuf field: fibertest30.ft.enums.ChannelEvent onMainChannel = 6;
     */
    onMainChannel: ChannelEvent;
    /**
     * @generated from protobuf field: fibertest30.ft.enums.ChannelEvent onReserveChannel = 7;
     */
    onReserveChannel: ChannelEvent;
}
/**
 * @generated from protobuf message fibertest30.events.data.BopEvent
 */
export interface BopEvent {
    /**
     * @generated from protobuf field: int32 eventId = 1;
     */
    eventId: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp registeredAt = 2;
     */
    registeredAt?: Timestamp;
    /**
     * @generated from protobuf field: string bopAddress = 3;
     */
    bopAddress: string;
    /**
     * @generated from protobuf field: string rtuId = 4;
     */
    rtuId: string;
    /**
     * @generated from protobuf field: string rtuTitle = 5;
     */
    rtuTitle: string;
    /**
     * @generated from protobuf field: string serial = 6;
     */
    serial: string;
    /**
     * @generated from protobuf field: bool isBopOk = 7;
     */
    isBopOk: boolean;
}
/**
 * @generated from protobuf message fibertest30.events.data.RtuAccident
 */
export interface RtuAccident {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: bool isMeasurementProblem = 2;
     */
    isMeasurementProblem: boolean;
    /**
     * @generated from protobuf field: int32 returnCode = 3;
     */
    returnCode: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp registeredAt = 4;
     */
    registeredAt?: Timestamp;
    /**
     * @generated from protobuf field: string rtuTitle = 5;
     */
    rtuTitle: string;
    /**
     * @generated from protobuf field: string rtuId = 6;
     */
    rtuId: string;
    /**
     * @generated from protobuf field: string traceTitle = 7;
     */
    traceTitle: string;
    /**
     * @generated from protobuf field: string traceId = 8;
     */
    traceId: string;
    /**
     * @generated from protobuf field: fibertest30.ft.enums.BaseRefType baseRefType = 9;
     */
    baseRefType: BaseRefType;
    /**
     * @generated from protobuf field: string comment = 10;
     */
    comment: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class DateTimeRange$Type extends MessageType<DateTimeRange> {
    constructor() {
        super("fibertest30.events.data.DateTimeRange", [
            { no: 1, name: "start", kind: "message", T: () => Timestamp },
            { no: 2, name: "end", kind: "message", T: () => Timestamp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.events.data.DateTimeRange
 */
export const DateTimeRange = new DateTimeRange$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DateTimeFilter$Type extends MessageType<DateTimeFilter> {
    constructor() {
        super("fibertest30.events.data.DateTimeFilter", [
            { no: 1, name: "searchWindow", kind: "message", T: () => DateTimeRange },
            { no: 2, name: "relativeFromNow", kind: "message", T: () => Duration },
            { no: 3, name: "loadSince", kind: "message", T: () => Timestamp },
            { no: 4, name: "orderDescending", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.events.data.DateTimeFilter
 */
export const DateTimeFilter = new DateTimeFilter$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OpticalEvent$Type extends MessageType<OpticalEvent> {
    constructor() {
        super("fibertest30.events.data.OpticalEvent", [
            { no: 1, name: "eventId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "measuredAt", kind: "message", T: () => Timestamp },
            { no: 3, name: "registeredAt", kind: "message", T: () => Timestamp },
            { no: 4, name: "rtuTitle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "rtuId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "traceTitle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "traceId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "baseRefType", kind: "enum", T: () => ["fibertest30.ft.enums.BaseRefType", BaseRefType] },
            { no: 9, name: "traceState", kind: "enum", T: () => ["fibertest30.ft.enums.FiberState", FiberState] },
            { no: 10, name: "eventStatus", kind: "enum", T: () => ["fibertest30.ft.enums.EventStatus", EventStatus] },
            { no: 11, name: "statusChangedAt", kind: "message", T: () => Timestamp },
            { no: 12, name: "statusChangedByUser", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "comment", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.events.data.OpticalEvent
 */
export const OpticalEvent = new OpticalEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NetworkEvent$Type extends MessageType<NetworkEvent> {
    constructor() {
        super("fibertest30.events.data.NetworkEvent", [
            { no: 1, name: "eventId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "registeredAt", kind: "message", T: () => Timestamp },
            { no: 3, name: "rtuId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "rtuTitle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "isRtuAvailable", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "onMainChannel", kind: "enum", T: () => ["fibertest30.ft.enums.ChannelEvent", ChannelEvent] },
            { no: 7, name: "onReserveChannel", kind: "enum", T: () => ["fibertest30.ft.enums.ChannelEvent", ChannelEvent] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.events.data.NetworkEvent
 */
export const NetworkEvent = new NetworkEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BopEvent$Type extends MessageType<BopEvent> {
    constructor() {
        super("fibertest30.events.data.BopEvent", [
            { no: 1, name: "eventId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "registeredAt", kind: "message", T: () => Timestamp },
            { no: 3, name: "bopAddress", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "rtuId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "rtuTitle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "serial", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "isBopOk", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.events.data.BopEvent
 */
export const BopEvent = new BopEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RtuAccident$Type extends MessageType<RtuAccident> {
    constructor() {
        super("fibertest30.events.data.RtuAccident", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "isMeasurementProblem", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "returnCode", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "registeredAt", kind: "message", T: () => Timestamp },
            { no: 5, name: "rtuTitle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "rtuId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "traceTitle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "traceId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "baseRefType", kind: "enum", T: () => ["fibertest30.ft.enums.BaseRefType", BaseRefType] },
            { no: 10, name: "comment", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.events.data.RtuAccident
 */
export const RtuAccident = new RtuAccident$Type();
