// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "ft.code.proto" (package "fibertest30.ft.code", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum fibertest30.ft.code.ReturnCode
 */
export enum ReturnCode {
    /**
     * @generated from protobuf enum value: Error = 0;
     */
    Error = 0,
    /**
     * @generated from protobuf enum value: Ok = 1;
     */
    Ok = 1,
    /**
     * @generated from protobuf enum value: InProgress = 2;
     */
    InProgress = 2,
    /**
     * @generated from protobuf enum value: TimeOutExpired = 3;
     */
    TimeOutExpired = 3,
    /**
     * @generated from protobuf enum value: NotFound = 4;
     */
    NotFound = 4,
    /**
     * not the same server that has initialized this RTU earlier
     *
     * @generated from protobuf enum value: WrongDataCenter = 5;
     */
    WrongDataCenter = 5,
    /**
     * @generated from protobuf enum value: RtuInitializationError = 1000;
     */
    RtuInitializationError = 1000,
    /**
     * @generated from protobuf enum value: RtuInitializedSuccessfully = 1001;
     */
    RtuInitializedSuccessfully = 1001,
    /**
     * @generated from protobuf enum value: OtdrInitializationCannotLoadDll = 1002;
     */
    OtdrInitializationCannotLoadDll = 1002,
    /**
     * @generated from protobuf enum value: OtdrInitializationCannotInitializeDll = 1003;
     */
    OtdrInitializationCannotInitializeDll = 1003,
    /**
     * @generated from protobuf enum value: FailedToConnectOtdr = 1004;
     */
    FailedToConnectOtdr = 1004,
    /**
     * @generated from protobuf enum value: OtauInitializationError = 1005;
     */
    OtauInitializationError = 1005,
    /**
     * @generated from protobuf enum value: CharonComPortError = 1006;
     */
    CharonComPortError = 1006,
    /**
     * Veex
     *
     * @generated from protobuf enum value: OtdrInitializationFailed = 1007;
     */
    OtdrInitializationFailed = 1007,
    /**
     * @generated from protobuf enum value: RtuUnauthorizedAccess = 1008;
     */
    RtuUnauthorizedAccess = 1008,
    /**
     * @generated from protobuf enum value: RtuDoesNotSupportBop = 1012;
     */
    RtuDoesNotSupportBop = 1012,
    /**
     * @generated from protobuf enum value: RtuTooBigPortNumber = 1013;
     */
    RtuTooBigPortNumber = 1013,
    /**
     * @generated from protobuf enum value: RtuIsBusy = 1100;
     */
    RtuIsBusy = 1100,
    /**
     * @generated from protobuf enum value: RtuInitializationInProgress = 1101;
     */
    RtuInitializationInProgress = 1101,
    /**
     * @generated from protobuf enum value: RtuAutoBaseMeasurementInProgress = 1102;
     */
    RtuAutoBaseMeasurementInProgress = 1102,
    /**
     * @generated from protobuf enum value: RtuBaseRefAssignmentError = 1106;
     */
    RtuBaseRefAssignmentError = 1106,
    /**
     * @generated from protobuf enum value: RtuMonitoringSettingsApplyError = 1107;
     */
    RtuMonitoringSettingsApplyError = 1107,
    /**
     * @generated from protobuf enum value: RtuAttachOtauError = 1108;
     */
    RtuAttachOtauError = 1108,
    /**
     * @generated from protobuf enum value: RtuDetachOtauError = 1109;
     */
    RtuDetachOtauError = 1109,
    /**
     * @generated from protobuf enum value: RtuToggleToPortError = 1110;
     */
    RtuToggleToPortError = 1110,
    /**
     * @generated from protobuf enum value: RtuToggleToBopPortError = 1111;
     */
    RtuToggleToBopPortError = 1111,
    /**
     * @generated from protobuf enum value: InvalidValueOfLmax = 1121;
     */
    InvalidValueOfLmax = 1121,
    /**
     * @generated from protobuf enum value: SnrIs0 = 1122;
     */
    SnrIs0 = 1122,
    /**
     * @generated from protobuf enum value: MeasurementError = 1500;
     */
    MeasurementError = 1500,
    /**
     * @generated from protobuf enum value: MeasurementEndedNormally = 1501;
     */
    MeasurementEndedNormally = 1501,
    /**
     * by Initialization + RTU serial changed
     *
     * @generated from protobuf enum value: MeasurementErrorCleared = 1502;
     */
    MeasurementErrorCleared = 1502,
    /**
     * RTU the same
     *
     * @generated from protobuf enum value: MeasurementErrorClearedByInit = 1503;
     */
    MeasurementErrorClearedByInit = 1503,
    /**
     * @generated from protobuf enum value: MeasurementPreparationError = 1510;
     */
    MeasurementPreparationError = 1510,
    /**
     * @generated from protobuf enum value: MeasurementToggleToPortFailed = 1511;
     */
    MeasurementToggleToPortFailed = 1511,
    /**
     * @generated from protobuf enum value: MeasurementBaseRefNotFound = 1512;
     */
    MeasurementBaseRefNotFound = 1512,
    /**
     * @generated from protobuf enum value: MeasurementFailedToSetParametersFromBase = 1513;
     */
    MeasurementFailedToSetParametersFromBase = 1513,
    /**
     * @generated from protobuf enum value: MeasurementHardwareProblem = 1520;
     */
    MeasurementHardwareProblem = 1520,
    /**
     * @generated from protobuf enum value: MeasurementAnalysisFailed = 1530;
     */
    MeasurementAnalysisFailed = 1530,
    /**
     * @generated from protobuf enum value: MeasurementComparisonFailed = 1532;
     */
    MeasurementComparisonFailed = 1532,
    /**
     * @generated from protobuf enum value: MeasurementInterrupted = 1590;
     */
    MeasurementInterrupted = 1590,
    /**
     * @generated from protobuf enum value: MeasurementTimeoutExpired = 1595;
     */
    MeasurementTimeoutExpired = 1595,
    /**
     * @generated from protobuf enum value: RtuFrequentServiceRestarts = 1600;
     */
    RtuFrequentServiceRestarts = 1600,
    /**
     * @generated from protobuf enum value: RtuManagerServiceWorking = 1601;
     */
    RtuManagerServiceWorking = 1601,
    /**
     * @generated from protobuf enum value: TcpConnectionError = 2000;
     */
    TcpConnectionError = 2000,
    /**
     * @generated from protobuf enum value: C2DWcfConnectionError = 2001;
     */
    C2DWcfConnectionError = 2001,
    /**
     * @generated from protobuf enum value: C2DWcfOperationError = 2002;
     */
    C2DWcfOperationError = 2002,
    /**
     * @generated from protobuf enum value: D2RWcfConnectionError = 2011;
     */
    D2RWcfConnectionError = 2011,
    /**
     * @generated from protobuf enum value: D2RWcfOperationError = 2012;
     */
    D2RWcfOperationError = 2012,
    /**
     * @generated from protobuf enum value: C2RWcfConnectionError = 2021;
     */
    C2RWcfConnectionError = 2021,
    /**
     * @generated from protobuf enum value: C2RWcfOperationError = 2022;
     */
    C2RWcfOperationError = 2022,
    /**
     * @generated from protobuf enum value: D2RHttpError = 2100;
     */
    D2RHttpError = 2100,
    /**
     * @generated from protobuf enum value: SerializationError = 2201;
     */
    SerializationError = 2201,
    /**
     * @generated from protobuf enum value: DeserializationError = 2202;
     */
    DeserializationError = 2202,
    /**
     * @generated from protobuf enum value: UnknownCommand = 2211;
     */
    UnknownCommand = 2211,
    /**
     * @generated from protobuf enum value: DbError = 3000;
     */
    DbError = 3000,
    /**
     * @generated from protobuf enum value: DbInitializedSuccessfully = 3001;
     */
    DbInitializedSuccessfully = 3001,
    /**
     * @generated from protobuf enum value: DbIsNotInitializedError = 3002;
     */
    DbIsNotInitializedError = 3002,
    /**
     * @generated from protobuf enum value: DbCannotConvertThisReSendToAssign = 3003;
     */
    DbCannotConvertThisReSendToAssign = 3003,
    /**
     * @generated from protobuf enum value: DbEntityToUpdateNotFound = 3004;
     */
    DbEntityToUpdateNotFound = 3004,
    /**
     * @generated from protobuf enum value: BaseRefAssignedSuccessfully = 4001;
     */
    BaseRefAssignedSuccessfully = 4001,
    /**
     * @generated from protobuf enum value: OtauAttachedSuccessfully = 4003;
     */
    OtauAttachedSuccessfully = 4003,
    /**
     * @generated from protobuf enum value: OtauDetachedSuccessfully = 4004;
     */
    OtauDetachedSuccessfully = 4004,
    /**
     * @generated from protobuf enum value: LandmarkChangesAppliedSuccessfully = 5000;
     */
    LandmarkChangesAppliedSuccessfully = 5000,
    /**
     * @generated from protobuf enum value: FailedToApplyLandmarkChanges = 5001;
     */
    FailedToApplyLandmarkChanges = 5001,
    /**
     * @generated from protobuf enum value: FailedToGetBaseRefs = 5011;
     */
    FailedToGetBaseRefs = 5011,
    /**
     * @generated from protobuf enum value: BaseRefsForTraceModifiedSuccessfully = 5020;
     */
    BaseRefsForTraceModifiedSuccessfully = 5020,
    /**
     * @generated from protobuf enum value: FailedToModifyBaseRef = 5021;
     */
    FailedToModifyBaseRef = 5021,
    /**
     * @generated from protobuf enum value: BaseRefsSavedSuccessfully = 5030;
     */
    BaseRefsSavedSuccessfully = 5030,
    /**
     * @generated from protobuf enum value: FailedToSaveBaseRefs = 5031;
     */
    FailedToSaveBaseRefs = 5031,
    /**
     * @generated from protobuf enum value: BaseRefsForTraceSentSuccessfully = 5040;
     */
    BaseRefsForTraceSentSuccessfully = 5040,
    /**
     * @generated from protobuf enum value: FailedToSendBaseToRtu = 5041;
     */
    FailedToSendBaseToRtu = 5041,
    /**
     * @generated from protobuf enum value: FailedToUpdateVeexTestList = 5042;
     */
    FailedToUpdateVeexTestList = 5042,
    /**
     * @generated from protobuf enum value: BaseRefsAmendmentProcessDone = 5050;
     */
    BaseRefsAmendmentProcessDone = 5050,
    /**
     * @generated from protobuf enum value: RtuInitializedAndBaseRefsResentSuccessfully = 5100;
     */
    RtuInitializedAndBaseRefsResentSuccessfully = 5100,
    /**
     * @generated from protobuf enum value: RtuInitializedFailedToReSendBaseRefs = 5101;
     */
    RtuInitializedFailedToReSendBaseRefs = 5101,
    /**
     * @generated from protobuf enum value: MonitoringSettingsAppliedSuccessfully = 5110;
     */
    MonitoringSettingsAppliedSuccessfully = 5110,
    /**
     * @generated from protobuf enum value: FailedToApplyMonitoringSettings = 5111;
     */
    FailedToApplyMonitoringSettings = 5111,
    /**
     * @generated from protobuf enum value: ClientRegisteredSuccessfully = 9000;
     */
    ClientRegisteredSuccessfully = 9000,
    /**
     * @generated from protobuf enum value: NoSuchUserOrWrongPassword = 9001;
     */
    NoSuchUserOrWrongPassword = 9001,
    /**
     * @generated from protobuf enum value: ThisUserRegisteredFromAnotherDevice = 9002;
     */
    ThisUserRegisteredFromAnotherDevice = 9002,
    /**
     * @generated from protobuf enum value: NoSuchClientStation = 9003;
     */
    NoSuchClientStation = 9003,
    /**
     * @generated from protobuf enum value: NoSuchRtu = 9004;
     */
    NoSuchRtu = 9004,
    /**
     * @generated from protobuf enum value: ClientsCountExceeded = 9005;
     */
    ClientsCountExceeded = 9005,
    /**
     * @generated from protobuf enum value: ClientsCountLicenseExpired = 9006;
     */
    ClientsCountLicenseExpired = 9006,
    /**
     * @generated from protobuf enum value: WebClientsCountExceeded = 9007;
     */
    WebClientsCountExceeded = 9007,
    /**
     * @generated from protobuf enum value: WebClientsCountLicenseExpired = 9008;
     */
    WebClientsCountLicenseExpired = 9008,
    /**
     * @generated from protobuf enum value: SuperClientsCountExceeded = 9009;
     */
    SuperClientsCountExceeded = 9009,
    /**
     * @generated from protobuf enum value: SuperClientsCountLicenseExpired = 9010;
     */
    SuperClientsCountLicenseExpired = 9010,
    /**
     * @generated from protobuf enum value: UserHasNoRightsToStartClient = 9011;
     */
    UserHasNoRightsToStartClient = 9011,
    /**
     * @generated from protobuf enum value: UserHasNoRightsToStartSuperClient = 9012;
     */
    UserHasNoRightsToStartSuperClient = 9012,
    /**
     * @generated from protobuf enum value: UserHasNoRightsToStartWebClient = 9013;
     */
    UserHasNoRightsToStartWebClient = 9013,
    /**
     * @generated from protobuf enum value: VersionsDoNotMatch = 9014;
     */
    VersionsDoNotMatch = 9014,
    /**
     * @generated from protobuf enum value: WrongMachineKey = 9051;
     */
    WrongMachineKey = 9051,
    /**
     * @generated from protobuf enum value: WrongSecurityAdminPassword = 9052;
     */
    WrongSecurityAdminPassword = 9052,
    /**
     * @generated from protobuf enum value: EmptyMachineKey = 9053;
     */
    EmptyMachineKey = 9053,
    /**
     * @generated from protobuf enum value: SaveUsersMachineKey = 9054;
     */
    SaveUsersMachineKey = 9054,
    /**
     * @generated from protobuf enum value: NoLicenseHasBeenAppliedYet = 9099;
     */
    NoLicenseHasBeenAppliedYet = 9099,
    /**
     * @generated from protobuf enum value: NoSuchVeexTest = 9201;
     */
    NoSuchVeexTest = 9201,
    /**
     * @generated from protobuf enum value: BaseRefAssignmentFailed = 9401;
     */
    BaseRefAssignmentFailed = 9401,
    /**
     * @generated from protobuf enum value: BaseRefAssignmentParamNotAcceptable = 9402;
     */
    BaseRefAssignmentParamNotAcceptable = 9402,
    /**
     * @generated from protobuf enum value: BaseRefAssignmentNoThresholds = 9403;
     */
    BaseRefAssignmentNoThresholds = 9403,
    /**
     * @generated from protobuf enum value: BaseRefAssignmentLandmarkCountWrong = 9404;
     */
    BaseRefAssignmentLandmarkCountWrong = 9404,
    /**
     * @generated from protobuf enum value: BaseRefAssignmentEdgeLandmarksWrong = 9405;
     */
    BaseRefAssignmentEdgeLandmarksWrong = 9405,
    /**
     * @generated from protobuf enum value: FirstLicenseKeyMustNotBeIncremental = 9501;
     */
    FirstLicenseKeyMustNotBeIncremental = 9501,
    /**
     * @generated from protobuf enum value: LicenseCouldNotBeAppliedRepeatedly = 9502;
     */
    LicenseCouldNotBeAppliedRepeatedly = 9502,
    /**
     * @generated from protobuf enum value: LicenseCouldNotBeApplied = 9503;
     */
    LicenseCouldNotBeApplied = 9503,
    /**
     * @generated from protobuf enum value: MeasurementClientStartedSuccessfully = 9601;
     */
    MeasurementClientStartedSuccessfully = 9601,
    /**
     * @generated from protobuf enum value: FetchMeasurementFromRtu4000Failed = 9632;
     */
    FetchMeasurementFromRtu4000Failed = 9632
}
