// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "ft.enums.proto" (package "fibertest30.ft.enums", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum fibertest30.ft.enums.FiberState
 */
export enum FiberState {
    /**
     * @generated from protobuf enum value: NotInTrace = 0;
     */
    NotInTrace = 0,
    /**
     * @generated from protobuf enum value: NotJoined = 1;
     */
    NotJoined = 1,
    /**
     * can't be just Unknown
     *
     * @generated from protobuf enum value: FiberState_Unknown = 2;
     */
    FiberState_Unknown = 2,
    /**
     * @generated from protobuf enum value: NotInZone = 3;
     */
    NotInZone = 3,
    /**
     * can't be just Ok
     *
     * @generated from protobuf enum value: FiberState_Ok = 4;
     */
    FiberState_Ok = 4,
    /**
     * @generated from protobuf enum value: Suspicion = 5;
     */
    Suspicion = 5,
    /**
     * @generated from protobuf enum value: Minor = 6;
     */
    Minor = 6,
    /**
     * @generated from protobuf enum value: Major = 7;
     */
    Major = 7,
    /**
     * @generated from protobuf enum value: Critical = 8;
     */
    Critical = 8,
    /**
     * @generated from protobuf enum value: User = 9;
     */
    User = 9,
    /**
     * @generated from protobuf enum value: FiberBreak = 10;
     */
    FiberBreak = 10,
    /**
     * @generated from protobuf enum value: NoFiber = 11;
     */
    NoFiber = 11,
    /**
     * @generated from protobuf enum value: HighLighted = 14;
     */
    HighLighted = 14,
    /**
     * @generated from protobuf enum value: DistanceMeasurement = 15;
     */
    DistanceMeasurement = 15,
    /**
     * @generated from protobuf enum value: Nothing = -1;
     */
    Nothing = -1
}
/**
 * @generated from protobuf enum fibertest30.ft.enums.RtuMaker
 */
export enum RtuMaker {
    /**
     * @generated from protobuf enum value: Iit = 0;
     */
    Iit = 0,
    /**
     * @generated from protobuf enum value: Veex = 1;
     */
    Veex = 1
}
/**
 * @generated from protobuf enum fibertest30.ft.enums.RtuPartState
 */
export enum RtuPartState {
    /**
     * @generated from protobuf enum value: NotSetYet = 0;
     */
    NotSetYet = 0,
    /**
     * can't be just Ok
     *
     * @generated from protobuf enum value: RtuPartState_Ok = 1;
     */
    RtuPartState_Ok = 1,
    /**
     * @generated from protobuf enum value: Broken = -1;
     */
    Broken = -1
}
/**
 * @generated from protobuf enum fibertest30.ft.enums.MonitoringState
 */
export enum MonitoringState {
    /**
     * can't be just Unknown
     *
     * @generated from protobuf enum value: MonitoringState_Unknown = 0;
     */
    MonitoringState_Unknown = 0,
    /**
     * @generated from protobuf enum value: Off = 1;
     */
    Off = 1,
    /**
     * @generated from protobuf enum value: On = 2;
     */
    On = 2
}
/**
 * @generated from protobuf enum fibertest30.ft.enums.TceLinkState
 */
export enum TceLinkState {
    /**
     * @generated from protobuf enum value: NoLink = 0;
     */
    NoLink = 0,
    /**
     * @generated from protobuf enum value: SnmpTrapOff = 1;
     */
    SnmpTrapOff = 1,
    /**
     * @generated from protobuf enum value: SnmpTrapOn = 2;
     */
    SnmpTrapOn = 2
}
/**
 * @generated from protobuf enum fibertest30.ft.enums.BaseRefType
 */
export enum BaseRefType {
    /**
     * @generated from protobuf enum value: None = 0;
     */
    None = 0,
    /**
     * @generated from protobuf enum value: Precise = 1;
     */
    Precise = 1,
    /**
     * @generated from protobuf enum value: Fast = 2;
     */
    Fast = 2,
    /**
     * @generated from protobuf enum value: Additional = 3;
     */
    Additional = 3
}
/**
 * @generated from protobuf enum fibertest30.ft.enums.EventStatus
 */
export enum EventStatus {
    /**
     * @generated from protobuf enum value: Unprocessed = 0;
     */
    Unprocessed = 0,
    /**
     * only for trace statistics
     *
     * @generated from protobuf enum value: JustMeasurementNotAnEvent = -99;
     */
    JustMeasurementNotAnEvent = -99,
    /**
     * Ok or Suspicion (made by Fast)
     *
     * @generated from protobuf enum value: EventButNotAnAccident = -9;
     */
    EventButNotAnAccident = -9,
    /**
     * @generated from protobuf enum value: NotImportant = -3;
     */
    NotImportant = -3,
    /**
     * @generated from protobuf enum value: Planned = -2;
     */
    Planned = -2,
    /**
     * @generated from protobuf enum value: NotConfirmed = -1;
     */
    NotConfirmed = -1,
    /**
     * @generated from protobuf enum value: Suspended = 1;
     */
    Suspended = 1,
    /**
     * @generated from protobuf enum value: Confirmed = 2;
     */
    Confirmed = 2
}
