// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "measurement.proto" (package "fibertest30.measurement", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { TimeSettings } from "./data.core";
import { NetworkSettings } from "./data.core";
import { TrapReceiver } from "./data.core";
import { EmailServer } from "./data.core";
import { NotificationSettings } from "./data.core";
import { AlarmProfile } from "./data.core";
import { MonitoringPort } from "./data.core";
import { MonitoringSchedule } from "./data.core";
import { MonitoringPortStatus } from "./data.core";
import { MeasurementSettings } from "./data.otdr";
/**
 * @generated from protobuf message fibertest30.measurement.GetSorSampleRequest
 */
export interface GetSorSampleRequest {
}
/**
 * @generated from protobuf message fibertest30.measurement.GetSorSampleResponse
 */
export interface GetSorSampleResponse {
    /**
     * @generated from protobuf field: bytes sor = 1;
     */
    sor: Uint8Array;
}
// StartOnDemand

/**
 * @generated from protobuf message fibertest30.measurement.StartOnDemandRequest
 */
export interface StartOnDemandRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: fibertest30.data.otdr.MeasurementSettings measurementSettings = 2;
     */
    measurementSettings?: MeasurementSettings;
}
/**
 * @generated from protobuf message fibertest30.measurement.StartOnDemandResponse
 */
export interface StartOnDemandResponse {
    /**
     * @generated from protobuf field: string onDemandId = 1;
     */
    onDemandId: string;
}
/**
 *  GetOnDemandProgressTrace
 *
 * @generated from protobuf message fibertest30.measurement.GetOnDemandProgressTraceRequest
 */
export interface GetOnDemandProgressTraceRequest {
    /**
     * @generated from protobuf field: string onDemandId = 1;
     */
    onDemandId: string;
}
/**
 * @generated from protobuf message fibertest30.measurement.GetOnDemandProgressTraceResponse
 */
export interface GetOnDemandProgressTraceResponse {
    /**
     * @generated from protobuf field: bytes sor = 1;
     */
    sor: Uint8Array;
}
/**
 * StopOnDemand
 *
 * @generated from protobuf message fibertest30.measurement.StopOnDemandRequest
 */
export interface StopOnDemandRequest {
    /**
     * @generated from protobuf field: string onDemandId = 1;
     */
    onDemandId: string;
}
/**
 * @generated from protobuf message fibertest30.measurement.StopOnDemandResponse
 */
export interface StopOnDemandResponse {
}
/**
 * SetMonitoringPortStatus
 *
 * @generated from protobuf message fibertest30.measurement.SetMonitoringPortStatusRequest
 */
export interface SetMonitoringPortStatusRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: fibertest30.data.core.MonitoringPortStatus status = 2;
     */
    status: MonitoringPortStatus;
}
/**
 * @generated from protobuf message fibertest30.measurement.SetMonitoringPortStatusResponse
 */
export interface SetMonitoringPortStatusResponse {
}
/**
 * SetMonitoringPortSchedule
 *
 * @generated from protobuf message fibertest30.measurement.SetMonitoringPortScheduleRequest
 */
export interface SetMonitoringPortScheduleRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: fibertest30.data.core.MonitoringSchedule schedule = 2;
     */
    schedule?: MonitoringSchedule;
}
/**
 * @generated from protobuf message fibertest30.measurement.SetMonitoringPortScheduleResponse
 */
export interface SetMonitoringPortScheduleResponse {
}
/**
 * SetPortAlarmProfile
 *
 * @generated from protobuf message fibertest30.measurement.SetPortAlarmProfileRequest
 */
export interface SetPortAlarmProfileRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: int32 alarmProfileId = 2;
     */
    alarmProfileId: number;
}
/**
 * @generated from protobuf message fibertest30.measurement.SetPortAlarmProfileResponse
 */
export interface SetPortAlarmProfileResponse {
}
/**
 * SetMonitoringPortNote
 *
 * @generated from protobuf message fibertest30.measurement.SetMonitoringPortNoteRequest
 */
export interface SetMonitoringPortNoteRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: string note = 2;
     */
    note: string; // The name max length is 1000 characters.
}
/**
 *
 * Server sends SystemEventType.MonitoringPortStatusChanged event with MonitoringPortStatusChangedData via server streaming.
 * "MonitoringPortStatusChangedData": {
 * "MonitoringPortId": "int",
 * "Note": "string"
 * }
 *
 * @generated from protobuf message fibertest30.measurement.SetMonitoringPortNoteResponse
 */
export interface SetMonitoringPortNoteResponse {
}
// GetMonitoringPort

/**
 * @generated from protobuf message fibertest30.measurement.GetMonitoringPortRequest
 */
export interface GetMonitoringPortRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
}
/**
 * @generated from protobuf message fibertest30.measurement.GetMonitoringPortResponse
 */
export interface GetMonitoringPortResponse {
    /**
     * @generated from protobuf field: fibertest30.data.core.MonitoringPort monitoringPort = 1;
     */
    monitoringPort?: MonitoringPort;
}
// GetOtauMonitoringPorts

/**
 * @generated from protobuf message fibertest30.measurement.GetOtauMonitoringPortsRequest
 */
export interface GetOtauMonitoringPortsRequest {
    /**
     * @generated from protobuf field: int32 otauId = 1;
     */
    otauId: number;
}
/**
 * @generated from protobuf message fibertest30.measurement.GetOtauMonitoringPortsResponse
 */
export interface GetOtauMonitoringPortsResponse {
    /**
     * @generated from protobuf field: repeated fibertest30.data.core.MonitoringPort monitoringPorts = 1;
     */
    monitoringPorts: MonitoringPort[];
}
// StartBaselineSetup

/**
 * @generated from protobuf message fibertest30.measurement.StartBaselineSetupRequest
 */
export interface StartBaselineSetupRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: bool fullAutoMode = 2;
     */
    fullAutoMode: boolean;
    /**
     * @generated from protobuf field: fibertest30.data.otdr.MeasurementSettings measurementSettings = 3;
     */
    measurementSettings?: MeasurementSettings;
}
/**
 * @generated from protobuf message fibertest30.measurement.StartBaselineSetupResponse
 */
export interface StartBaselineSetupResponse {
}
// StopBaselineSetup

/**
 * @generated from protobuf message fibertest30.measurement.StopBaselineSetupRequest
 */
export interface StopBaselineSetupRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
}
/**
 * @generated from protobuf message fibertest30.measurement.StopBaselineSetupResponse
 */
export interface StopBaselineSetupResponse {
}
/**
 *  GetBaselineProgressTrace
 *
 * @generated from protobuf message fibertest30.measurement.GetBaselineProgressTraceRequest
 */
export interface GetBaselineProgressTraceRequest {
    /**
     * @generated from protobuf field: string taskId = 1;
     */
    taskId: string;
}
/**
 * @generated from protobuf message fibertest30.measurement.GetBaselineProgressTraceResponse
 */
export interface GetBaselineProgressTraceResponse {
    /**
     * @generated from protobuf field: bytes sor = 1;
     */
    sor: Uint8Array;
}
// 

/**
 * GetAllAlarmProfiles
 *
 * @generated from protobuf message fibertest30.measurement.GetAllAlarmProfilesRequest
 */
export interface GetAllAlarmProfilesRequest {
}
/**
 * @generated from protobuf message fibertest30.measurement.GetAllAlarmProfilesResponse
 */
export interface GetAllAlarmProfilesResponse {
    /**
     * @generated from protobuf field: repeated fibertest30.data.core.AlarmProfile alarmProfiles = 1;
     */
    alarmProfiles: AlarmProfile[];
}
/**
 * UpdateAlarmProfile
 *
 * @generated from protobuf message fibertest30.measurement.UpdateAlarmProfileRequest
 */
export interface UpdateAlarmProfileRequest {
    /**
     * @generated from protobuf field: fibertest30.data.core.AlarmProfile alarmProfile = 1;
     */
    alarmProfile?: AlarmProfile;
}
/**
 * @generated from protobuf message fibertest30.measurement.UpdateAlarmProfileResponse
 */
export interface UpdateAlarmProfileResponse {
}
/**
 * GetAlarmProfile
 *
 * @generated from protobuf message fibertest30.measurement.GetAlarmProfileRequest
 */
export interface GetAlarmProfileRequest {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
}
/**
 * @generated from protobuf message fibertest30.measurement.GetAlarmProfileResponse
 */
export interface GetAlarmProfileResponse {
    /**
     * @generated from protobuf field: fibertest30.data.core.AlarmProfile alarmProfile = 1;
     */
    alarmProfile?: AlarmProfile;
}
/**
 * CreateAlarmProfile
 *
 * @generated from protobuf message fibertest30.measurement.CreateAlarmProfileRequest
 */
export interface CreateAlarmProfileRequest {
    /**
     * @generated from protobuf field: fibertest30.data.core.AlarmProfile alarmProfile = 1;
     */
    alarmProfile?: AlarmProfile;
}
/**
 * @generated from protobuf message fibertest30.measurement.CreateAlarmProfileResponse
 */
export interface CreateAlarmProfileResponse {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
}
/**
 * DeleteAlarmProfile
 *
 * @generated from protobuf message fibertest30.measurement.DeleteAlarmProfileRequest
 */
export interface DeleteAlarmProfileRequest {
    /**
     * @generated from protobuf field: int32 alarmProfileId = 1;
     */
    alarmProfileId: number;
}
/**
 * @generated from protobuf message fibertest30.measurement.DeleteAlarmProfileResponse
 */
export interface DeleteAlarmProfileResponse {
}
/**
 * UpdateNotificationSettings
 *
 * @generated from protobuf message fibertest30.measurement.UpdateNotificationSettingsRequest
 */
export interface UpdateNotificationSettingsRequest {
    /**
     * @generated from protobuf field: fibertest30.data.core.NotificationSettings notificationSettings = 1;
     */
    notificationSettings?: NotificationSettings;
}
/**
 * @generated from protobuf message fibertest30.measurement.UpdateNotificationSettingsResponse
 */
export interface UpdateNotificationSettingsResponse {
}
/**
 * GetNotificationSettings
 *
 * @generated from protobuf message fibertest30.measurement.GetNotificationSettingsRequest
 */
export interface GetNotificationSettingsRequest {
}
/**
 * @generated from protobuf message fibertest30.measurement.GetNotificationSettingsResponse
 */
export interface GetNotificationSettingsResponse {
    /**
     * @generated from protobuf field: fibertest30.data.core.NotificationSettings notificationSettings = 1;
     */
    notificationSettings?: NotificationSettings;
}
/**
 * TestEmailServerSettings
 *
 * @generated from protobuf message fibertest30.measurement.TestEmailServerSettingsRequest
 */
export interface TestEmailServerSettingsRequest {
    /**
     * @generated from protobuf field: fibertest30.data.core.EmailServer emailServer = 1;
     */
    emailServer?: EmailServer;
}
/**
 * @generated from protobuf message fibertest30.measurement.TestEmailServerSettingsResponse
 */
export interface TestEmailServerSettingsResponse {
}
/**
 * TestTrapReceiverSettings
 *
 * @generated from protobuf message fibertest30.measurement.TestTrapReceiverSettingsRequest
 */
export interface TestTrapReceiverSettingsRequest {
    /**
     * @generated from protobuf field: fibertest30.data.core.TrapReceiver trapReceiver = 1;
     */
    trapReceiver?: TrapReceiver;
}
/**
 * @generated from protobuf message fibertest30.measurement.TestTrapReceiverSettingsResponse
 */
export interface TestTrapReceiverSettingsResponse {
}
/**
 * GetNetworkSettings
 *
 * @generated from protobuf message fibertest30.measurement.GetNetworkSettingsRequest
 */
export interface GetNetworkSettingsRequest {
}
/**
 * @generated from protobuf message fibertest30.measurement.GetNetworkSettingsResponse
 */
export interface GetNetworkSettingsResponse {
    /**
     * @generated from protobuf field: fibertest30.data.core.NetworkSettings networkSettings = 1;
     */
    networkSettings?: NetworkSettings;
}
/**
 * UpdateNetworkSettings
 *
 * @generated from protobuf message fibertest30.measurement.UpdateNetworkSettingsRequest
 */
export interface UpdateNetworkSettingsRequest {
    /**
     * @generated from protobuf field: fibertest30.data.core.NetworkSettings networkSettings = 1;
     */
    networkSettings?: NetworkSettings;
}
/**
 * @generated from protobuf message fibertest30.measurement.UpdateNetworkSettingsResponse
 */
export interface UpdateNetworkSettingsResponse {
}
/**
 * GetTimeSettings
 *
 * @generated from protobuf message fibertest30.measurement.GetTimeSettingsRequest
 */
export interface GetTimeSettingsRequest {
}
/**
 * @generated from protobuf message fibertest30.measurement.GetTimeSettingsResponse
 */
export interface GetTimeSettingsResponse {
    /**
     * @generated from protobuf field: fibertest30.data.core.TimeSettings timeSettings = 1;
     */
    timeSettings?: TimeSettings;
}
/**
 * UpdateTiemSettings
 *
 * @generated from protobuf message fibertest30.measurement.UpdateTimeSettingsRequest
 */
export interface UpdateTimeSettingsRequest {
    /**
     * @generated from protobuf field: fibertest30.data.core.TimeSettings timeSettings = 1;
     */
    timeSettings?: TimeSettings;
}
/**
 * @generated from protobuf message fibertest30.measurement.UpdateTimeSettingsResponse
 */
export interface UpdateTimeSettingsResponse {
}
// @generated message type with reflection information, may provide speed optimized methods
class GetSorSampleRequest$Type extends MessageType<GetSorSampleRequest> {
    constructor() {
        super("fibertest30.measurement.GetSorSampleRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetSorSampleRequest
 */
export const GetSorSampleRequest = new GetSorSampleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSorSampleResponse$Type extends MessageType<GetSorSampleResponse> {
    constructor() {
        super("fibertest30.measurement.GetSorSampleResponse", [
            { no: 1, name: "sor", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetSorSampleResponse
 */
export const GetSorSampleResponse = new GetSorSampleResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StartOnDemandRequest$Type extends MessageType<StartOnDemandRequest> {
    constructor() {
        super("fibertest30.measurement.StartOnDemandRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "measurementSettings", kind: "message", T: () => MeasurementSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.StartOnDemandRequest
 */
export const StartOnDemandRequest = new StartOnDemandRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StartOnDemandResponse$Type extends MessageType<StartOnDemandResponse> {
    constructor() {
        super("fibertest30.measurement.StartOnDemandResponse", [
            { no: 1, name: "onDemandId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.StartOnDemandResponse
 */
export const StartOnDemandResponse = new StartOnDemandResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOnDemandProgressTraceRequest$Type extends MessageType<GetOnDemandProgressTraceRequest> {
    constructor() {
        super("fibertest30.measurement.GetOnDemandProgressTraceRequest", [
            { no: 1, name: "onDemandId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetOnDemandProgressTraceRequest
 */
export const GetOnDemandProgressTraceRequest = new GetOnDemandProgressTraceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOnDemandProgressTraceResponse$Type extends MessageType<GetOnDemandProgressTraceResponse> {
    constructor() {
        super("fibertest30.measurement.GetOnDemandProgressTraceResponse", [
            { no: 1, name: "sor", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetOnDemandProgressTraceResponse
 */
export const GetOnDemandProgressTraceResponse = new GetOnDemandProgressTraceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StopOnDemandRequest$Type extends MessageType<StopOnDemandRequest> {
    constructor() {
        super("fibertest30.measurement.StopOnDemandRequest", [
            { no: 1, name: "onDemandId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.StopOnDemandRequest
 */
export const StopOnDemandRequest = new StopOnDemandRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StopOnDemandResponse$Type extends MessageType<StopOnDemandResponse> {
    constructor() {
        super("fibertest30.measurement.StopOnDemandResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.StopOnDemandResponse
 */
export const StopOnDemandResponse = new StopOnDemandResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetMonitoringPortStatusRequest$Type extends MessageType<SetMonitoringPortStatusRequest> {
    constructor() {
        super("fibertest30.measurement.SetMonitoringPortStatusRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "status", kind: "enum", T: () => ["fibertest30.data.core.MonitoringPortStatus", MonitoringPortStatus] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.SetMonitoringPortStatusRequest
 */
export const SetMonitoringPortStatusRequest = new SetMonitoringPortStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetMonitoringPortStatusResponse$Type extends MessageType<SetMonitoringPortStatusResponse> {
    constructor() {
        super("fibertest30.measurement.SetMonitoringPortStatusResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.SetMonitoringPortStatusResponse
 */
export const SetMonitoringPortStatusResponse = new SetMonitoringPortStatusResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetMonitoringPortScheduleRequest$Type extends MessageType<SetMonitoringPortScheduleRequest> {
    constructor() {
        super("fibertest30.measurement.SetMonitoringPortScheduleRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "schedule", kind: "message", T: () => MonitoringSchedule }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.SetMonitoringPortScheduleRequest
 */
export const SetMonitoringPortScheduleRequest = new SetMonitoringPortScheduleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetMonitoringPortScheduleResponse$Type extends MessageType<SetMonitoringPortScheduleResponse> {
    constructor() {
        super("fibertest30.measurement.SetMonitoringPortScheduleResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.SetMonitoringPortScheduleResponse
 */
export const SetMonitoringPortScheduleResponse = new SetMonitoringPortScheduleResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetPortAlarmProfileRequest$Type extends MessageType<SetPortAlarmProfileRequest> {
    constructor() {
        super("fibertest30.measurement.SetPortAlarmProfileRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "alarmProfileId", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.SetPortAlarmProfileRequest
 */
export const SetPortAlarmProfileRequest = new SetPortAlarmProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetPortAlarmProfileResponse$Type extends MessageType<SetPortAlarmProfileResponse> {
    constructor() {
        super("fibertest30.measurement.SetPortAlarmProfileResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.SetPortAlarmProfileResponse
 */
export const SetPortAlarmProfileResponse = new SetPortAlarmProfileResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetMonitoringPortNoteRequest$Type extends MessageType<SetMonitoringPortNoteRequest> {
    constructor() {
        super("fibertest30.measurement.SetMonitoringPortNoteRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "note", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.SetMonitoringPortNoteRequest
 */
export const SetMonitoringPortNoteRequest = new SetMonitoringPortNoteRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetMonitoringPortNoteResponse$Type extends MessageType<SetMonitoringPortNoteResponse> {
    constructor() {
        super("fibertest30.measurement.SetMonitoringPortNoteResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.SetMonitoringPortNoteResponse
 */
export const SetMonitoringPortNoteResponse = new SetMonitoringPortNoteResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringPortRequest$Type extends MessageType<GetMonitoringPortRequest> {
    constructor() {
        super("fibertest30.measurement.GetMonitoringPortRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetMonitoringPortRequest
 */
export const GetMonitoringPortRequest = new GetMonitoringPortRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringPortResponse$Type extends MessageType<GetMonitoringPortResponse> {
    constructor() {
        super("fibertest30.measurement.GetMonitoringPortResponse", [
            { no: 1, name: "monitoringPort", kind: "message", T: () => MonitoringPort }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetMonitoringPortResponse
 */
export const GetMonitoringPortResponse = new GetMonitoringPortResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOtauMonitoringPortsRequest$Type extends MessageType<GetOtauMonitoringPortsRequest> {
    constructor() {
        super("fibertest30.measurement.GetOtauMonitoringPortsRequest", [
            { no: 1, name: "otauId", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetOtauMonitoringPortsRequest
 */
export const GetOtauMonitoringPortsRequest = new GetOtauMonitoringPortsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOtauMonitoringPortsResponse$Type extends MessageType<GetOtauMonitoringPortsResponse> {
    constructor() {
        super("fibertest30.measurement.GetOtauMonitoringPortsResponse", [
            { no: 1, name: "monitoringPorts", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MonitoringPort }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetOtauMonitoringPortsResponse
 */
export const GetOtauMonitoringPortsResponse = new GetOtauMonitoringPortsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StartBaselineSetupRequest$Type extends MessageType<StartBaselineSetupRequest> {
    constructor() {
        super("fibertest30.measurement.StartBaselineSetupRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "fullAutoMode", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "measurementSettings", kind: "message", T: () => MeasurementSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.StartBaselineSetupRequest
 */
export const StartBaselineSetupRequest = new StartBaselineSetupRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StartBaselineSetupResponse$Type extends MessageType<StartBaselineSetupResponse> {
    constructor() {
        super("fibertest30.measurement.StartBaselineSetupResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.StartBaselineSetupResponse
 */
export const StartBaselineSetupResponse = new StartBaselineSetupResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StopBaselineSetupRequest$Type extends MessageType<StopBaselineSetupRequest> {
    constructor() {
        super("fibertest30.measurement.StopBaselineSetupRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.StopBaselineSetupRequest
 */
export const StopBaselineSetupRequest = new StopBaselineSetupRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StopBaselineSetupResponse$Type extends MessageType<StopBaselineSetupResponse> {
    constructor() {
        super("fibertest30.measurement.StopBaselineSetupResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.StopBaselineSetupResponse
 */
export const StopBaselineSetupResponse = new StopBaselineSetupResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBaselineProgressTraceRequest$Type extends MessageType<GetBaselineProgressTraceRequest> {
    constructor() {
        super("fibertest30.measurement.GetBaselineProgressTraceRequest", [
            { no: 1, name: "taskId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetBaselineProgressTraceRequest
 */
export const GetBaselineProgressTraceRequest = new GetBaselineProgressTraceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBaselineProgressTraceResponse$Type extends MessageType<GetBaselineProgressTraceResponse> {
    constructor() {
        super("fibertest30.measurement.GetBaselineProgressTraceResponse", [
            { no: 1, name: "sor", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetBaselineProgressTraceResponse
 */
export const GetBaselineProgressTraceResponse = new GetBaselineProgressTraceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllAlarmProfilesRequest$Type extends MessageType<GetAllAlarmProfilesRequest> {
    constructor() {
        super("fibertest30.measurement.GetAllAlarmProfilesRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetAllAlarmProfilesRequest
 */
export const GetAllAlarmProfilesRequest = new GetAllAlarmProfilesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllAlarmProfilesResponse$Type extends MessageType<GetAllAlarmProfilesResponse> {
    constructor() {
        super("fibertest30.measurement.GetAllAlarmProfilesResponse", [
            { no: 1, name: "alarmProfiles", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AlarmProfile }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetAllAlarmProfilesResponse
 */
export const GetAllAlarmProfilesResponse = new GetAllAlarmProfilesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateAlarmProfileRequest$Type extends MessageType<UpdateAlarmProfileRequest> {
    constructor() {
        super("fibertest30.measurement.UpdateAlarmProfileRequest", [
            { no: 1, name: "alarmProfile", kind: "message", T: () => AlarmProfile }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.UpdateAlarmProfileRequest
 */
export const UpdateAlarmProfileRequest = new UpdateAlarmProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateAlarmProfileResponse$Type extends MessageType<UpdateAlarmProfileResponse> {
    constructor() {
        super("fibertest30.measurement.UpdateAlarmProfileResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.UpdateAlarmProfileResponse
 */
export const UpdateAlarmProfileResponse = new UpdateAlarmProfileResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAlarmProfileRequest$Type extends MessageType<GetAlarmProfileRequest> {
    constructor() {
        super("fibertest30.measurement.GetAlarmProfileRequest", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetAlarmProfileRequest
 */
export const GetAlarmProfileRequest = new GetAlarmProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAlarmProfileResponse$Type extends MessageType<GetAlarmProfileResponse> {
    constructor() {
        super("fibertest30.measurement.GetAlarmProfileResponse", [
            { no: 1, name: "alarmProfile", kind: "message", T: () => AlarmProfile }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetAlarmProfileResponse
 */
export const GetAlarmProfileResponse = new GetAlarmProfileResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateAlarmProfileRequest$Type extends MessageType<CreateAlarmProfileRequest> {
    constructor() {
        super("fibertest30.measurement.CreateAlarmProfileRequest", [
            { no: 1, name: "alarmProfile", kind: "message", T: () => AlarmProfile }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.CreateAlarmProfileRequest
 */
export const CreateAlarmProfileRequest = new CreateAlarmProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateAlarmProfileResponse$Type extends MessageType<CreateAlarmProfileResponse> {
    constructor() {
        super("fibertest30.measurement.CreateAlarmProfileResponse", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.CreateAlarmProfileResponse
 */
export const CreateAlarmProfileResponse = new CreateAlarmProfileResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteAlarmProfileRequest$Type extends MessageType<DeleteAlarmProfileRequest> {
    constructor() {
        super("fibertest30.measurement.DeleteAlarmProfileRequest", [
            { no: 1, name: "alarmProfileId", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.DeleteAlarmProfileRequest
 */
export const DeleteAlarmProfileRequest = new DeleteAlarmProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteAlarmProfileResponse$Type extends MessageType<DeleteAlarmProfileResponse> {
    constructor() {
        super("fibertest30.measurement.DeleteAlarmProfileResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.DeleteAlarmProfileResponse
 */
export const DeleteAlarmProfileResponse = new DeleteAlarmProfileResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateNotificationSettingsRequest$Type extends MessageType<UpdateNotificationSettingsRequest> {
    constructor() {
        super("fibertest30.measurement.UpdateNotificationSettingsRequest", [
            { no: 1, name: "notificationSettings", kind: "message", T: () => NotificationSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.UpdateNotificationSettingsRequest
 */
export const UpdateNotificationSettingsRequest = new UpdateNotificationSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateNotificationSettingsResponse$Type extends MessageType<UpdateNotificationSettingsResponse> {
    constructor() {
        super("fibertest30.measurement.UpdateNotificationSettingsResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.UpdateNotificationSettingsResponse
 */
export const UpdateNotificationSettingsResponse = new UpdateNotificationSettingsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetNotificationSettingsRequest$Type extends MessageType<GetNotificationSettingsRequest> {
    constructor() {
        super("fibertest30.measurement.GetNotificationSettingsRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetNotificationSettingsRequest
 */
export const GetNotificationSettingsRequest = new GetNotificationSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetNotificationSettingsResponse$Type extends MessageType<GetNotificationSettingsResponse> {
    constructor() {
        super("fibertest30.measurement.GetNotificationSettingsResponse", [
            { no: 1, name: "notificationSettings", kind: "message", T: () => NotificationSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetNotificationSettingsResponse
 */
export const GetNotificationSettingsResponse = new GetNotificationSettingsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TestEmailServerSettingsRequest$Type extends MessageType<TestEmailServerSettingsRequest> {
    constructor() {
        super("fibertest30.measurement.TestEmailServerSettingsRequest", [
            { no: 1, name: "emailServer", kind: "message", T: () => EmailServer }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.TestEmailServerSettingsRequest
 */
export const TestEmailServerSettingsRequest = new TestEmailServerSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TestEmailServerSettingsResponse$Type extends MessageType<TestEmailServerSettingsResponse> {
    constructor() {
        super("fibertest30.measurement.TestEmailServerSettingsResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.TestEmailServerSettingsResponse
 */
export const TestEmailServerSettingsResponse = new TestEmailServerSettingsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TestTrapReceiverSettingsRequest$Type extends MessageType<TestTrapReceiverSettingsRequest> {
    constructor() {
        super("fibertest30.measurement.TestTrapReceiverSettingsRequest", [
            { no: 1, name: "trapReceiver", kind: "message", T: () => TrapReceiver }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.TestTrapReceiverSettingsRequest
 */
export const TestTrapReceiverSettingsRequest = new TestTrapReceiverSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TestTrapReceiverSettingsResponse$Type extends MessageType<TestTrapReceiverSettingsResponse> {
    constructor() {
        super("fibertest30.measurement.TestTrapReceiverSettingsResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.TestTrapReceiverSettingsResponse
 */
export const TestTrapReceiverSettingsResponse = new TestTrapReceiverSettingsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetNetworkSettingsRequest$Type extends MessageType<GetNetworkSettingsRequest> {
    constructor() {
        super("fibertest30.measurement.GetNetworkSettingsRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetNetworkSettingsRequest
 */
export const GetNetworkSettingsRequest = new GetNetworkSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetNetworkSettingsResponse$Type extends MessageType<GetNetworkSettingsResponse> {
    constructor() {
        super("fibertest30.measurement.GetNetworkSettingsResponse", [
            { no: 1, name: "networkSettings", kind: "message", T: () => NetworkSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetNetworkSettingsResponse
 */
export const GetNetworkSettingsResponse = new GetNetworkSettingsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateNetworkSettingsRequest$Type extends MessageType<UpdateNetworkSettingsRequest> {
    constructor() {
        super("fibertest30.measurement.UpdateNetworkSettingsRequest", [
            { no: 1, name: "networkSettings", kind: "message", T: () => NetworkSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.UpdateNetworkSettingsRequest
 */
export const UpdateNetworkSettingsRequest = new UpdateNetworkSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateNetworkSettingsResponse$Type extends MessageType<UpdateNetworkSettingsResponse> {
    constructor() {
        super("fibertest30.measurement.UpdateNetworkSettingsResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.UpdateNetworkSettingsResponse
 */
export const UpdateNetworkSettingsResponse = new UpdateNetworkSettingsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTimeSettingsRequest$Type extends MessageType<GetTimeSettingsRequest> {
    constructor() {
        super("fibertest30.measurement.GetTimeSettingsRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetTimeSettingsRequest
 */
export const GetTimeSettingsRequest = new GetTimeSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTimeSettingsResponse$Type extends MessageType<GetTimeSettingsResponse> {
    constructor() {
        super("fibertest30.measurement.GetTimeSettingsResponse", [
            { no: 1, name: "timeSettings", kind: "message", T: () => TimeSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.GetTimeSettingsResponse
 */
export const GetTimeSettingsResponse = new GetTimeSettingsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTimeSettingsRequest$Type extends MessageType<UpdateTimeSettingsRequest> {
    constructor() {
        super("fibertest30.measurement.UpdateTimeSettingsRequest", [
            { no: 1, name: "timeSettings", kind: "message", T: () => TimeSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.UpdateTimeSettingsRequest
 */
export const UpdateTimeSettingsRequest = new UpdateTimeSettingsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTimeSettingsResponse$Type extends MessageType<UpdateTimeSettingsResponse> {
    constructor() {
        super("fibertest30.measurement.UpdateTimeSettingsResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.measurement.UpdateTimeSettingsResponse
 */
export const UpdateTimeSettingsResponse = new UpdateTimeSettingsResponse$Type();
/**
 * @generated ServiceType for protobuf service fibertest30.measurement.Measurement
 */
export const Measurement = new ServiceType("fibertest30.measurement.Measurement", [
    { name: "GetSorSample", options: {}, I: GetSorSampleRequest, O: GetSorSampleResponse },
    { name: "StartOnDemand", options: {}, I: StartOnDemandRequest, O: StartOnDemandResponse },
    { name: "GetOnDemandProgressTrace", options: {}, I: GetOnDemandProgressTraceRequest, O: GetOnDemandProgressTraceResponse },
    { name: "StopOnDemand", options: {}, I: StopOnDemandRequest, O: StopOnDemandResponse },
    { name: "SetMonitoringPortStatus", options: {}, I: SetMonitoringPortStatusRequest, O: SetMonitoringPortStatusResponse },
    { name: "GetMonitoringPort", options: {}, I: GetMonitoringPortRequest, O: GetMonitoringPortResponse },
    { name: "GetOtauMonitoringPorts", options: {}, I: GetOtauMonitoringPortsRequest, O: GetOtauMonitoringPortsResponse },
    { name: "SetMonitoringPortSchedule", options: {}, I: SetMonitoringPortScheduleRequest, O: SetMonitoringPortScheduleResponse },
    { name: "SetPortAlarmProfile", options: {}, I: SetPortAlarmProfileRequest, O: SetPortAlarmProfileResponse },
    { name: "SetMonitoringPortNote", options: {}, I: SetMonitoringPortNoteRequest, O: SetMonitoringPortNoteResponse },
    { name: "StartBaselineSetup", options: {}, I: StartBaselineSetupRequest, O: StartBaselineSetupResponse },
    { name: "StopBaselineSetup", options: {}, I: StopBaselineSetupRequest, O: StopBaselineSetupResponse },
    { name: "GetBaselineProgressTrace", options: {}, I: GetBaselineProgressTraceRequest, O: GetBaselineProgressTraceResponse },
    { name: "GetAllAlarmProfiles", options: {}, I: GetAllAlarmProfilesRequest, O: GetAllAlarmProfilesResponse },
    { name: "UpdateAlarmProfile", options: {}, I: UpdateAlarmProfileRequest, O: UpdateAlarmProfileResponse },
    { name: "GetAlarmProfile", options: {}, I: GetAlarmProfileRequest, O: GetAlarmProfileResponse },
    { name: "CreateAlarmProfile", options: {}, I: CreateAlarmProfileRequest, O: CreateAlarmProfileResponse },
    { name: "DeleteAlarmProfile", options: {}, I: DeleteAlarmProfileRequest, O: DeleteAlarmProfileResponse },
    { name: "UpdateNotificationSettings", options: {}, I: UpdateNotificationSettingsRequest, O: UpdateNotificationSettingsResponse },
    { name: "GetNotificationSettings", options: {}, I: GetNotificationSettingsRequest, O: GetNotificationSettingsResponse },
    { name: "TestEmailServerSettings", options: {}, I: TestEmailServerSettingsRequest, O: TestEmailServerSettingsResponse },
    { name: "TestTrapReceiverSettings", options: {}, I: TestTrapReceiverSettingsRequest, O: TestTrapReceiverSettingsResponse },
    { name: "GetNetworkSettings", options: {}, I: GetNetworkSettingsRequest, O: GetNetworkSettingsResponse },
    { name: "UpdateNetworkSettings", options: {}, I: UpdateNetworkSettingsRequest, O: UpdateNetworkSettingsResponse },
    { name: "GetTimeSettings", options: {}, I: GetTimeSettingsRequest, O: GetTimeSettingsResponse },
    { name: "UpdateTimeSettings", options: {}, I: UpdateTimeSettingsRequest, O: UpdateTimeSettingsResponse }
]);
