// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "reporting.proto" (package "fibertest30.reporting", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { MonitoringAlarmEvent } from "./data.monitoring";
import { MonitoringBaseline } from "./data.core";
import { DateTimeFilter } from "./data.reporting";
import { MonitoringAlarmLevel } from "./data.monitoring";
import { MeasurementSettings } from "./data.otdr";
import { Timestamp } from "./google/protobuf/timestamp";
import { SystemEvent } from "./data.core";
import { MonitoringAlarm } from "./data.monitoring";
// GetAlarm

/**
 * @generated from protobuf message fibertest30.reporting.GetAlarmRequest
 */
export interface GetAlarmRequest {
    /**
     * @generated from protobuf field: int32 Id = 1 [json_name = "Id"];
     */
    id: number;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetAlarmResponse
 */
export interface GetAlarmResponse {
    /**
     * @generated from protobuf field: fibertest30.data.monitoring.MonitoringAlarm alarm = 1;
     */
    alarm?: MonitoringAlarm;
}
// GetActiveAlarmsRequest

/**
 * @generated from protobuf message fibertest30.reporting.GetActiveAlarmsRequest
 */
export interface GetActiveAlarmsRequest {
}
/**
 * @generated from protobuf message fibertest30.reporting.GetActiveAlarmsResponse
 */
export interface GetActiveAlarmsResponse {
    /**
     * @generated from protobuf field: repeated fibertest30.data.monitoring.MonitoringAlarm activeAlarms = 1;
     */
    activeAlarms: MonitoringAlarm[];
}
/**
 * GetAllAlarms
 *
 * @generated from protobuf message fibertest30.reporting.GetAllAlarmsRequest
 */
export interface GetAllAlarmsRequest {
    /**
     * @generated from protobuf field: repeated int32 monitoringPortIds = 1;
     */
    monitoringPortIds: number[];
}
/**
 * @generated from protobuf message fibertest30.reporting.GetAllAlarmsResponse
 */
export interface GetAllAlarmsResponse {
    /**
     * @generated from protobuf field: repeated fibertest30.data.monitoring.MonitoringAlarm allAlarms = 1;
     */
    allAlarms: MonitoringAlarm[];
}
// GetSystemEvents

/**
 * @generated from protobuf message fibertest30.reporting.GetSystemEventsRequest
 */
export interface GetSystemEventsRequest {
}
/**
 * @generated from protobuf message fibertest30.reporting.GetSystemEventsResponse
 */
export interface GetSystemEventsResponse {
    /**
     * @generated from protobuf field: repeated fibertest30.data.core.SystemEvent systemEvents = 1;
     */
    systemEvents: SystemEvent[];
}
// GetOnDemands

/**
 * @generated from protobuf message fibertest30.reporting.CompletedOnDemand
 */
export interface CompletedOnDemand {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string CreatedByUserId = 2 [json_name = "CreatedByUserId"];
     */
    createdByUserId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp completedAt = 3;
     */
    completedAt?: Timestamp;
    /**
     * @generated from protobuf field: int32 monitoringPortId = 4;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: fibertest30.data.otdr.MeasurementSettings measurementSettings = 5;
     */
    measurementSettings?: MeasurementSettings;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetOnDemandsRequest
 */
export interface GetOnDemandsRequest {
    /**
     * @generated from protobuf field: repeated int32 monitoringPortIds = 1;
     */
    monitoringPortIds: number[];
}
/**
 * @generated from protobuf message fibertest30.reporting.GetOnDemandsResponse
 */
export interface GetOnDemandsResponse {
    /**
     * @generated from protobuf field: repeated fibertest30.reporting.CompletedOnDemand onDemands = 1;
     */
    onDemands: CompletedOnDemand[];
}
// GetOnDemand

/**
 * @generated from protobuf message fibertest30.reporting.GetOnDemandRequest
 */
export interface GetOnDemandRequest {
    /**
     * @generated from protobuf field: string onDemandId = 1;
     */
    onDemandId: string;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetOnDemandResponse
 */
export interface GetOnDemandResponse {
    /**
     * @generated from protobuf field: fibertest30.reporting.CompletedOnDemand onDemand = 1;
     */
    onDemand?: CompletedOnDemand;
}
// GetOnDemandTrace

/**
 * @generated from protobuf message fibertest30.reporting.GetOnDemandTraceRequest
 */
export interface GetOnDemandTraceRequest {
    /**
     * @generated from protobuf field: string onDemandId = 1;
     */
    onDemandId: string;
    /**
     * @generated from protobuf field: bool vxsorFormat = 2;
     */
    vxsorFormat: boolean;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetOnDemandTraceResponse
 */
export interface GetOnDemandTraceResponse {
    /**
     * @generated from protobuf field: bytes sor = 1;
     */
    sor: Uint8Array;
}
// GetOnDemandLinkmap

/**
 * @generated from protobuf message fibertest30.reporting.GetOnDemandLinkmapRequest
 */
export interface GetOnDemandLinkmapRequest {
    /**
     * @generated from protobuf field: string onDemandId = 1;
     */
    onDemandId: string;
    /**
     * @generated from protobuf field: double macrobendThreshold = 2;
     */
    macrobendThreshold: number;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetOnDemandLinkmapResponse
 */
export interface GetOnDemandLinkmapResponse {
    /**
     * @generated from protobuf field: bytes lmap = 1;
     */
    lmap: Uint8Array;
}
// GetMonitorings

/**
 * @generated from protobuf message fibertest30.reporting.MonitoringResult
 */
export interface MonitoringResult {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp completedAt = 2;
     */
    completedAt?: Timestamp;
    /**
     * @generated from protobuf field: int32 monitoringPortId = 3;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: fibertest30.data.otdr.MeasurementSettings measurementSettings = 4;
     */
    measurementSettings?: MeasurementSettings;
    /**
     * @generated from protobuf field: int32 baselineId = 5;
     */
    baselineId: number;
    /**
     * @generated from protobuf field: fibertest30.data.monitoring.MonitoringAlarmLevel mostSevereChangeLevel = 6;
     */
    mostSevereChangeLevel: MonitoringAlarmLevel;
    /**
     * @generated from protobuf field: int32 changesCount = 7;
     */
    changesCount: number;
    /**
     * @generated from protobuf field: string jsonChanges = 8;
     */
    jsonChanges: string;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetMonitoringsRequest
 */
export interface GetMonitoringsRequest {
    /**
     * @generated from protobuf field: repeated int32 monitoringPortIds = 1;
     */
    monitoringPortIds: number[];
    /**
     * @generated from protobuf field: fibertest30.data.reporting.DateTimeFilter dateTimeFilter = 2;
     */
    dateTimeFilter?: DateTimeFilter;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetMonitoringsResponse
 */
export interface GetMonitoringsResponse {
    /**
     * @generated from protobuf field: repeated fibertest30.reporting.MonitoringResult monitorings = 1;
     */
    monitorings: MonitoringResult[];
}
// GetMonitoring

/**
 * @generated from protobuf message fibertest30.reporting.GetMonitoringRequest
 */
export interface GetMonitoringRequest {
    /**
     * @generated from protobuf field: int32 monitoringId = 1;
     */
    monitoringId: number;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetMonitoringResponse
 */
export interface GetMonitoringResponse {
    /**
     * @generated from protobuf field: fibertest30.reporting.MonitoringResult monitoring = 1;
     */
    monitoring?: MonitoringResult;
}
// GetMonitoringTrace

/**
 * @generated from protobuf message fibertest30.reporting.GetMonitoringTraceRequest
 */
export interface GetMonitoringTraceRequest {
    /**
     * @generated from protobuf field: int32 monitoringId = 1;
     */
    monitoringId: number;
    /**
     * @generated from protobuf field: bool vxsorFormat = 2;
     */
    vxsorFormat: boolean;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetMonitoringTraceResponse
 */
export interface GetMonitoringTraceResponse {
    /**
     * @generated from protobuf field: bytes sor = 1;
     */
    sor: Uint8Array;
}
// GetMonitoringLinkmap

/**
 * @generated from protobuf message fibertest30.reporting.GetMonitoringLinkmapRequest
 */
export interface GetMonitoringLinkmapRequest {
    /**
     * @generated from protobuf field: int32 monitoringId = 1;
     */
    monitoringId: number;
    /**
     * @generated from protobuf field: double macrobendThreshold = 2;
     */
    macrobendThreshold: number;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetMonitoringLinkmapResponse
 */
export interface GetMonitoringLinkmapResponse {
    /**
     * @generated from protobuf field: bytes lmap = 1;
     */
    lmap: Uint8Array;
}
/**
 * GetBaselines
 *
 * @generated from protobuf message fibertest30.reporting.GetBaselinesRequest
 */
export interface GetBaselinesRequest {
    /**
     * @generated from protobuf field: repeated int32 monitoringPortIds = 1;
     */
    monitoringPortIds: number[];
}
/**
 * @generated from protobuf message fibertest30.reporting.GetBaselinesResponse
 */
export interface GetBaselinesResponse {
    /**
     * @generated from protobuf field: repeated fibertest30.data.core.MonitoringBaseline baselines = 1;
     */
    baselines: MonitoringBaseline[];
}
// GetBaseline

/**
 * @generated from protobuf message fibertest30.reporting.GetBaselineRequest
 */
export interface GetBaselineRequest {
    /**
     * @generated from protobuf field: int32 baselineId = 1;
     */
    baselineId: number;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetBaselineResponse
 */
export interface GetBaselineResponse {
    /**
     * @generated from protobuf field: fibertest30.data.core.MonitoringBaseline baseline = 1;
     */
    baseline?: MonitoringBaseline;
}
// GetBaselineTrace 

/**
 * @generated from protobuf message fibertest30.reporting.GetBaselineTraceRequest
 */
export interface GetBaselineTraceRequest {
    /**
     * @generated from protobuf field: int32 baselineId = 1;
     */
    baselineId: number;
    /**
     * @generated from protobuf field: bool vxsorFormat = 2;
     */
    vxsorFormat: boolean;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetBaselineTraceResponse
 */
export interface GetBaselineTraceResponse {
    /**
     * @generated from protobuf field: bytes sor = 1;
     */
    sor: Uint8Array;
}
// GetBaselineLinkmap 

/**
 * @generated from protobuf message fibertest30.reporting.GetBaselineLinkmapRequest
 */
export interface GetBaselineLinkmapRequest {
    /**
     * @generated from protobuf field: int32 baselineId = 1;
     */
    baselineId: number;
    /**
     * @generated from protobuf field: double macrobendThreshold = 2;
     */
    macrobendThreshold: number;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetBaselineLinkmapResponse
 */
export interface GetBaselineLinkmapResponse {
    /**
     * @generated from protobuf field: bytes lmap = 1;
     */
    lmap: Uint8Array;
}
/**
 * GetMonitoringTraceAndBase
 *
 * @generated from protobuf message fibertest30.reporting.GetMonitoringTraceAndBaseRequest
 */
export interface GetMonitoringTraceAndBaseRequest {
    /**
     * @generated from protobuf field: int32 monitoringId = 1;
     */
    monitoringId: number;
    /**
     * @generated from protobuf field: bool vxsorFormat = 2;
     */
    vxsorFormat: boolean;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetMonitoringTraceAndBaseResponse
 */
export interface GetMonitoringTraceAndBaseResponse {
    /**
     * @generated from protobuf field: bytes archive = 1;
     */
    archive: Uint8Array;
}
// GetAlarmEvents

/**
 * @generated from protobuf message fibertest30.reporting.GetAlarmEventsRequest
 */
export interface GetAlarmEventsRequest {
    /**
     * @generated from protobuf field: repeated int32 monitoringPortIds = 1;
     */
    monitoringPortIds: number[];
}
/**
 * @generated from protobuf message fibertest30.reporting.GetAlarmEventsResponse
 */
export interface GetAlarmEventsResponse {
    /**
     * @generated from protobuf field: repeated fibertest30.data.monitoring.MonitoringAlarmEvent alarmEvents = 1;
     */
    alarmEvents: MonitoringAlarmEvent[];
}
// GetLastMonitoring

/**
 * @generated from protobuf message fibertest30.reporting.GetLastMonitoringRequest
 */
export interface GetLastMonitoringRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: int32 baselineId = 2;
     */
    baselineId: number;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetLastMonitoringResponse
 */
export interface GetLastMonitoringResponse {
    /**
     * @generated from protobuf field: fibertest30.reporting.MonitoringResult monitoring = 1;
     */
    monitoring?: MonitoringResult;
}
// GetLastMonitoringTrace

/**
 * @generated from protobuf message fibertest30.reporting.GetLastMonitoringTraceRequest
 */
export interface GetLastMonitoringTraceRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: int32 baselineId = 2;
     */
    baselineId: number;
    /**
     * @generated from protobuf field: bool vxsorFormat = 3;
     */
    vxsorFormat: boolean;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetLastMonitoringTraceResponse
 */
export interface GetLastMonitoringTraceResponse {
    /**
     * @generated from protobuf field: bytes sor = 1;
     */
    sor: Uint8Array;
}
// GetLastMonitoringLinkmap

/**
 * @generated from protobuf message fibertest30.reporting.GetLastMonitoringLinkmapRequest
 */
export interface GetLastMonitoringLinkmapRequest {
    /**
     * @generated from protobuf field: int32 monitoringPortId = 1;
     */
    monitoringPortId: number;
    /**
     * @generated from protobuf field: int32 baselineId = 2;
     */
    baselineId: number;
    /**
     * @generated from protobuf field: double macrobendThreshold = 3;
     */
    macrobendThreshold: number;
}
/**
 * @generated from protobuf message fibertest30.reporting.GetLastMonitoringLinkmapResponse
 */
export interface GetLastMonitoringLinkmapResponse {
    /**
     * @generated from protobuf field: bytes lmap = 1;
     */
    lmap: Uint8Array;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetAlarmRequest$Type extends MessageType<GetAlarmRequest> {
    constructor() {
        super("fibertest30.reporting.GetAlarmRequest", [
            { no: 1, name: "Id", kind: "scalar", jsonName: "Id", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetAlarmRequest
 */
export const GetAlarmRequest = new GetAlarmRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAlarmResponse$Type extends MessageType<GetAlarmResponse> {
    constructor() {
        super("fibertest30.reporting.GetAlarmResponse", [
            { no: 1, name: "alarm", kind: "message", T: () => MonitoringAlarm }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetAlarmResponse
 */
export const GetAlarmResponse = new GetAlarmResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActiveAlarmsRequest$Type extends MessageType<GetActiveAlarmsRequest> {
    constructor() {
        super("fibertest30.reporting.GetActiveAlarmsRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetActiveAlarmsRequest
 */
export const GetActiveAlarmsRequest = new GetActiveAlarmsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetActiveAlarmsResponse$Type extends MessageType<GetActiveAlarmsResponse> {
    constructor() {
        super("fibertest30.reporting.GetActiveAlarmsResponse", [
            { no: 1, name: "activeAlarms", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MonitoringAlarm }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetActiveAlarmsResponse
 */
export const GetActiveAlarmsResponse = new GetActiveAlarmsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllAlarmsRequest$Type extends MessageType<GetAllAlarmsRequest> {
    constructor() {
        super("fibertest30.reporting.GetAllAlarmsRequest", [
            { no: 1, name: "monitoringPortIds", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetAllAlarmsRequest
 */
export const GetAllAlarmsRequest = new GetAllAlarmsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAllAlarmsResponse$Type extends MessageType<GetAllAlarmsResponse> {
    constructor() {
        super("fibertest30.reporting.GetAllAlarmsResponse", [
            { no: 1, name: "allAlarms", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MonitoringAlarm }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetAllAlarmsResponse
 */
export const GetAllAlarmsResponse = new GetAllAlarmsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSystemEventsRequest$Type extends MessageType<GetSystemEventsRequest> {
    constructor() {
        super("fibertest30.reporting.GetSystemEventsRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetSystemEventsRequest
 */
export const GetSystemEventsRequest = new GetSystemEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSystemEventsResponse$Type extends MessageType<GetSystemEventsResponse> {
    constructor() {
        super("fibertest30.reporting.GetSystemEventsResponse", [
            { no: 1, name: "systemEvents", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => SystemEvent }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetSystemEventsResponse
 */
export const GetSystemEventsResponse = new GetSystemEventsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CompletedOnDemand$Type extends MessageType<CompletedOnDemand> {
    constructor() {
        super("fibertest30.reporting.CompletedOnDemand", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "CreatedByUserId", kind: "scalar", jsonName: "CreatedByUserId", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "completedAt", kind: "message", T: () => Timestamp },
            { no: 4, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "measurementSettings", kind: "message", T: () => MeasurementSettings }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.CompletedOnDemand
 */
export const CompletedOnDemand = new CompletedOnDemand$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOnDemandsRequest$Type extends MessageType<GetOnDemandsRequest> {
    constructor() {
        super("fibertest30.reporting.GetOnDemandsRequest", [
            { no: 1, name: "monitoringPortIds", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetOnDemandsRequest
 */
export const GetOnDemandsRequest = new GetOnDemandsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOnDemandsResponse$Type extends MessageType<GetOnDemandsResponse> {
    constructor() {
        super("fibertest30.reporting.GetOnDemandsResponse", [
            { no: 1, name: "onDemands", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => CompletedOnDemand }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetOnDemandsResponse
 */
export const GetOnDemandsResponse = new GetOnDemandsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOnDemandRequest$Type extends MessageType<GetOnDemandRequest> {
    constructor() {
        super("fibertest30.reporting.GetOnDemandRequest", [
            { no: 1, name: "onDemandId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetOnDemandRequest
 */
export const GetOnDemandRequest = new GetOnDemandRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOnDemandResponse$Type extends MessageType<GetOnDemandResponse> {
    constructor() {
        super("fibertest30.reporting.GetOnDemandResponse", [
            { no: 1, name: "onDemand", kind: "message", T: () => CompletedOnDemand }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetOnDemandResponse
 */
export const GetOnDemandResponse = new GetOnDemandResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOnDemandTraceRequest$Type extends MessageType<GetOnDemandTraceRequest> {
    constructor() {
        super("fibertest30.reporting.GetOnDemandTraceRequest", [
            { no: 1, name: "onDemandId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "vxsorFormat", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetOnDemandTraceRequest
 */
export const GetOnDemandTraceRequest = new GetOnDemandTraceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOnDemandTraceResponse$Type extends MessageType<GetOnDemandTraceResponse> {
    constructor() {
        super("fibertest30.reporting.GetOnDemandTraceResponse", [
            { no: 1, name: "sor", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetOnDemandTraceResponse
 */
export const GetOnDemandTraceResponse = new GetOnDemandTraceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOnDemandLinkmapRequest$Type extends MessageType<GetOnDemandLinkmapRequest> {
    constructor() {
        super("fibertest30.reporting.GetOnDemandLinkmapRequest", [
            { no: 1, name: "onDemandId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "macrobendThreshold", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetOnDemandLinkmapRequest
 */
export const GetOnDemandLinkmapRequest = new GetOnDemandLinkmapRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetOnDemandLinkmapResponse$Type extends MessageType<GetOnDemandLinkmapResponse> {
    constructor() {
        super("fibertest30.reporting.GetOnDemandLinkmapResponse", [
            { no: 1, name: "lmap", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetOnDemandLinkmapResponse
 */
export const GetOnDemandLinkmapResponse = new GetOnDemandLinkmapResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MonitoringResult$Type extends MessageType<MonitoringResult> {
    constructor() {
        super("fibertest30.reporting.MonitoringResult", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "completedAt", kind: "message", T: () => Timestamp },
            { no: 3, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "measurementSettings", kind: "message", T: () => MeasurementSettings },
            { no: 5, name: "baselineId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "mostSevereChangeLevel", kind: "enum", T: () => ["fibertest30.data.monitoring.MonitoringAlarmLevel", MonitoringAlarmLevel] },
            { no: 7, name: "changesCount", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "jsonChanges", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.MonitoringResult
 */
export const MonitoringResult = new MonitoringResult$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringsRequest$Type extends MessageType<GetMonitoringsRequest> {
    constructor() {
        super("fibertest30.reporting.GetMonitoringsRequest", [
            { no: 1, name: "monitoringPortIds", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "dateTimeFilter", kind: "message", T: () => DateTimeFilter }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetMonitoringsRequest
 */
export const GetMonitoringsRequest = new GetMonitoringsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringsResponse$Type extends MessageType<GetMonitoringsResponse> {
    constructor() {
        super("fibertest30.reporting.GetMonitoringsResponse", [
            { no: 1, name: "monitorings", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MonitoringResult }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetMonitoringsResponse
 */
export const GetMonitoringsResponse = new GetMonitoringsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringRequest$Type extends MessageType<GetMonitoringRequest> {
    constructor() {
        super("fibertest30.reporting.GetMonitoringRequest", [
            { no: 1, name: "monitoringId", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetMonitoringRequest
 */
export const GetMonitoringRequest = new GetMonitoringRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringResponse$Type extends MessageType<GetMonitoringResponse> {
    constructor() {
        super("fibertest30.reporting.GetMonitoringResponse", [
            { no: 1, name: "monitoring", kind: "message", T: () => MonitoringResult }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetMonitoringResponse
 */
export const GetMonitoringResponse = new GetMonitoringResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringTraceRequest$Type extends MessageType<GetMonitoringTraceRequest> {
    constructor() {
        super("fibertest30.reporting.GetMonitoringTraceRequest", [
            { no: 1, name: "monitoringId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "vxsorFormat", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetMonitoringTraceRequest
 */
export const GetMonitoringTraceRequest = new GetMonitoringTraceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringTraceResponse$Type extends MessageType<GetMonitoringTraceResponse> {
    constructor() {
        super("fibertest30.reporting.GetMonitoringTraceResponse", [
            { no: 1, name: "sor", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetMonitoringTraceResponse
 */
export const GetMonitoringTraceResponse = new GetMonitoringTraceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringLinkmapRequest$Type extends MessageType<GetMonitoringLinkmapRequest> {
    constructor() {
        super("fibertest30.reporting.GetMonitoringLinkmapRequest", [
            { no: 1, name: "monitoringId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "macrobendThreshold", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetMonitoringLinkmapRequest
 */
export const GetMonitoringLinkmapRequest = new GetMonitoringLinkmapRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringLinkmapResponse$Type extends MessageType<GetMonitoringLinkmapResponse> {
    constructor() {
        super("fibertest30.reporting.GetMonitoringLinkmapResponse", [
            { no: 1, name: "lmap", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetMonitoringLinkmapResponse
 */
export const GetMonitoringLinkmapResponse = new GetMonitoringLinkmapResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBaselinesRequest$Type extends MessageType<GetBaselinesRequest> {
    constructor() {
        super("fibertest30.reporting.GetBaselinesRequest", [
            { no: 1, name: "monitoringPortIds", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetBaselinesRequest
 */
export const GetBaselinesRequest = new GetBaselinesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBaselinesResponse$Type extends MessageType<GetBaselinesResponse> {
    constructor() {
        super("fibertest30.reporting.GetBaselinesResponse", [
            { no: 1, name: "baselines", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MonitoringBaseline }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetBaselinesResponse
 */
export const GetBaselinesResponse = new GetBaselinesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBaselineRequest$Type extends MessageType<GetBaselineRequest> {
    constructor() {
        super("fibertest30.reporting.GetBaselineRequest", [
            { no: 1, name: "baselineId", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetBaselineRequest
 */
export const GetBaselineRequest = new GetBaselineRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBaselineResponse$Type extends MessageType<GetBaselineResponse> {
    constructor() {
        super("fibertest30.reporting.GetBaselineResponse", [
            { no: 1, name: "baseline", kind: "message", T: () => MonitoringBaseline }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetBaselineResponse
 */
export const GetBaselineResponse = new GetBaselineResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBaselineTraceRequest$Type extends MessageType<GetBaselineTraceRequest> {
    constructor() {
        super("fibertest30.reporting.GetBaselineTraceRequest", [
            { no: 1, name: "baselineId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "vxsorFormat", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetBaselineTraceRequest
 */
export const GetBaselineTraceRequest = new GetBaselineTraceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBaselineTraceResponse$Type extends MessageType<GetBaselineTraceResponse> {
    constructor() {
        super("fibertest30.reporting.GetBaselineTraceResponse", [
            { no: 1, name: "sor", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetBaselineTraceResponse
 */
export const GetBaselineTraceResponse = new GetBaselineTraceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBaselineLinkmapRequest$Type extends MessageType<GetBaselineLinkmapRequest> {
    constructor() {
        super("fibertest30.reporting.GetBaselineLinkmapRequest", [
            { no: 1, name: "baselineId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "macrobendThreshold", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetBaselineLinkmapRequest
 */
export const GetBaselineLinkmapRequest = new GetBaselineLinkmapRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBaselineLinkmapResponse$Type extends MessageType<GetBaselineLinkmapResponse> {
    constructor() {
        super("fibertest30.reporting.GetBaselineLinkmapResponse", [
            { no: 1, name: "lmap", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetBaselineLinkmapResponse
 */
export const GetBaselineLinkmapResponse = new GetBaselineLinkmapResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringTraceAndBaseRequest$Type extends MessageType<GetMonitoringTraceAndBaseRequest> {
    constructor() {
        super("fibertest30.reporting.GetMonitoringTraceAndBaseRequest", [
            { no: 1, name: "monitoringId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "vxsorFormat", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetMonitoringTraceAndBaseRequest
 */
export const GetMonitoringTraceAndBaseRequest = new GetMonitoringTraceAndBaseRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMonitoringTraceAndBaseResponse$Type extends MessageType<GetMonitoringTraceAndBaseResponse> {
    constructor() {
        super("fibertest30.reporting.GetMonitoringTraceAndBaseResponse", [
            { no: 1, name: "archive", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetMonitoringTraceAndBaseResponse
 */
export const GetMonitoringTraceAndBaseResponse = new GetMonitoringTraceAndBaseResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAlarmEventsRequest$Type extends MessageType<GetAlarmEventsRequest> {
    constructor() {
        super("fibertest30.reporting.GetAlarmEventsRequest", [
            { no: 1, name: "monitoringPortIds", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetAlarmEventsRequest
 */
export const GetAlarmEventsRequest = new GetAlarmEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAlarmEventsResponse$Type extends MessageType<GetAlarmEventsResponse> {
    constructor() {
        super("fibertest30.reporting.GetAlarmEventsResponse", [
            { no: 1, name: "alarmEvents", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MonitoringAlarmEvent }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetAlarmEventsResponse
 */
export const GetAlarmEventsResponse = new GetAlarmEventsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLastMonitoringRequest$Type extends MessageType<GetLastMonitoringRequest> {
    constructor() {
        super("fibertest30.reporting.GetLastMonitoringRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "baselineId", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetLastMonitoringRequest
 */
export const GetLastMonitoringRequest = new GetLastMonitoringRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLastMonitoringResponse$Type extends MessageType<GetLastMonitoringResponse> {
    constructor() {
        super("fibertest30.reporting.GetLastMonitoringResponse", [
            { no: 1, name: "monitoring", kind: "message", T: () => MonitoringResult }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetLastMonitoringResponse
 */
export const GetLastMonitoringResponse = new GetLastMonitoringResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLastMonitoringTraceRequest$Type extends MessageType<GetLastMonitoringTraceRequest> {
    constructor() {
        super("fibertest30.reporting.GetLastMonitoringTraceRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "baselineId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "vxsorFormat", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetLastMonitoringTraceRequest
 */
export const GetLastMonitoringTraceRequest = new GetLastMonitoringTraceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLastMonitoringTraceResponse$Type extends MessageType<GetLastMonitoringTraceResponse> {
    constructor() {
        super("fibertest30.reporting.GetLastMonitoringTraceResponse", [
            { no: 1, name: "sor", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetLastMonitoringTraceResponse
 */
export const GetLastMonitoringTraceResponse = new GetLastMonitoringTraceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLastMonitoringLinkmapRequest$Type extends MessageType<GetLastMonitoringLinkmapRequest> {
    constructor() {
        super("fibertest30.reporting.GetLastMonitoringLinkmapRequest", [
            { no: 1, name: "monitoringPortId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "baselineId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "macrobendThreshold", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetLastMonitoringLinkmapRequest
 */
export const GetLastMonitoringLinkmapRequest = new GetLastMonitoringLinkmapRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLastMonitoringLinkmapResponse$Type extends MessageType<GetLastMonitoringLinkmapResponse> {
    constructor() {
        super("fibertest30.reporting.GetLastMonitoringLinkmapResponse", [
            { no: 1, name: "lmap", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reporting.GetLastMonitoringLinkmapResponse
 */
export const GetLastMonitoringLinkmapResponse = new GetLastMonitoringLinkmapResponse$Type();
/**
 * @generated ServiceType for protobuf service fibertest30.reporting.Reporting
 */
export const Reporting = new ServiceType("fibertest30.reporting.Reporting", [
    { name: "GetAlarm", options: {}, I: GetAlarmRequest, O: GetAlarmResponse },
    { name: "GetActiveAlarms", options: {}, I: GetActiveAlarmsRequest, O: GetActiveAlarmsResponse },
    { name: "GetAllAlarms", options: {}, I: GetAllAlarmsRequest, O: GetAllAlarmsResponse },
    { name: "GetSystemEvents", options: {}, I: GetSystemEventsRequest, O: GetSystemEventsResponse },
    { name: "GetOnDemands", options: {}, I: GetOnDemandsRequest, O: GetOnDemandsResponse },
    { name: "GetOnDemand", options: {}, I: GetOnDemandRequest, O: GetOnDemandResponse },
    { name: "GetOnDemandTrace", options: {}, I: GetOnDemandTraceRequest, O: GetOnDemandTraceResponse },
    { name: "GetOnDemandLinkmap", options: {}, I: GetOnDemandLinkmapRequest, O: GetOnDemandLinkmapResponse },
    { name: "GetMonitorings", options: {}, I: GetMonitoringsRequest, O: GetMonitoringsResponse },
    { name: "GetMonitoring", options: {}, I: GetMonitoringRequest, O: GetMonitoringResponse },
    { name: "GetMonitoringTrace", options: {}, I: GetMonitoringTraceRequest, O: GetMonitoringTraceResponse },
    { name: "GetMonitoringLinkmap", options: {}, I: GetMonitoringLinkmapRequest, O: GetMonitoringLinkmapResponse },
    { name: "GetBaselines", options: {}, I: GetBaselinesRequest, O: GetBaselinesResponse },
    { name: "GetBaseline", options: {}, I: GetBaselineRequest, O: GetBaselineResponse },
    { name: "GetBaselineTrace", options: {}, I: GetBaselineTraceRequest, O: GetBaselineTraceResponse },
    { name: "GetBaselineLinkmap", options: {}, I: GetBaselineLinkmapRequest, O: GetBaselineLinkmapResponse },
    { name: "GetAlarmEvents", options: {}, I: GetAlarmEventsRequest, O: GetAlarmEventsResponse },
    { name: "GetLastMonitoring", options: {}, I: GetLastMonitoringRequest, O: GetLastMonitoringResponse },
    { name: "GetLastMonitoringTrace", options: {}, I: GetLastMonitoringTraceRequest, O: GetLastMonitoringTraceResponse },
    { name: "GetLastMonitoringLinkmap", options: {}, I: GetLastMonitoringLinkmapRequest, O: GetLastMonitoringLinkmapResponse },
    { name: "GetMonitoringTraceAndBase", options: {}, I: GetMonitoringTraceAndBaseRequest, O: GetMonitoringTraceAndBaseResponse }
]);
