// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "reports.proto" (package "fibertest30.reports", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { DateTimeFilter } from "./events.data";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message fibertest30.reports.UserActionLine
 */
export interface UserActionLine {
    /**
     * @generated from protobuf field: int32 ordinal = 1;
     */
    ordinal: number;
    /**
     * @generated from protobuf field: string username = 2;
     */
    username: string;
    /**
     * @generated from protobuf field: string clientIp = 3;
     */
    clientIp: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp registeredAt = 4;
     */
    registeredAt?: Timestamp;
    /**
     * @generated from protobuf field: int32 logOperationCode = 5;
     */
    logOperationCode: number;
    /**
     * @generated from protobuf field: string rtuTitle = 6;
     */
    rtuTitle: string;
    /**
     * @generated from protobuf field: string traceTitle = 7;
     */
    traceTitle: string;
    /**
     * @generated from protobuf field: string operationParams = 8;
     */
    operationParams: string;
}
/**
 * GetUserActionLines
 *
 * @generated from protobuf message fibertest30.reports.GetUserActionLinesRequest
 */
export interface GetUserActionLinesRequest {
    /**
     * @generated from protobuf field: string userId = 1;
     */
    userId: string;
    /**
     * @generated from protobuf field: fibertest30.events.data.DateTimeFilter dateTimeFilter = 2;
     */
    dateTimeFilter?: DateTimeFilter;
    /**
     * @generated from protobuf field: repeated int32 operationCodes = 3;
     */
    operationCodes: number[];
}
/**
 * @generated from protobuf message fibertest30.reports.GetUserActionLinesResponse
 */
export interface GetUserActionLinesResponse {
    /**
     * @generated from protobuf field: repeated fibertest30.reports.UserActionLine lines = 1;
     */
    lines: UserActionLine[];
}
/**
 * GetUserActonsPdf
 *
 * @generated from protobuf message fibertest30.reports.GetUserActonsPdfRequest
 */
export interface GetUserActonsPdfRequest {
    /**
     * @generated from protobuf field: string userId = 1;
     */
    userId: string;
    /**
     * @generated from protobuf field: fibertest30.events.data.DateTimeFilter dateTimeFilter = 2;
     */
    dateTimeFilter?: DateTimeFilter;
    /**
     * @generated from protobuf field: repeated int32 operationCodes = 3;
     */
    operationCodes: number[];
}
/**
 * @generated from protobuf message fibertest30.reports.GetUserActonsPdfResponse
 */
export interface GetUserActonsPdfResponse {
    /**
     * @generated from protobuf field: bytes pdf = 1;
     */
    pdf: Uint8Array;
}
// @generated message type with reflection information, may provide speed optimized methods
class UserActionLine$Type extends MessageType<UserActionLine> {
    constructor() {
        super("fibertest30.reports.UserActionLine", [
            { no: 1, name: "ordinal", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "clientIp", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "registeredAt", kind: "message", T: () => Timestamp },
            { no: 5, name: "logOperationCode", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "rtuTitle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "traceTitle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "operationParams", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reports.UserActionLine
 */
export const UserActionLine = new UserActionLine$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserActionLinesRequest$Type extends MessageType<GetUserActionLinesRequest> {
    constructor() {
        super("fibertest30.reports.GetUserActionLinesRequest", [
            { no: 1, name: "userId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "dateTimeFilter", kind: "message", T: () => DateTimeFilter },
            { no: 3, name: "operationCodes", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reports.GetUserActionLinesRequest
 */
export const GetUserActionLinesRequest = new GetUserActionLinesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserActionLinesResponse$Type extends MessageType<GetUserActionLinesResponse> {
    constructor() {
        super("fibertest30.reports.GetUserActionLinesResponse", [
            { no: 1, name: "lines", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => UserActionLine }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reports.GetUserActionLinesResponse
 */
export const GetUserActionLinesResponse = new GetUserActionLinesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserActonsPdfRequest$Type extends MessageType<GetUserActonsPdfRequest> {
    constructor() {
        super("fibertest30.reports.GetUserActonsPdfRequest", [
            { no: 1, name: "userId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "dateTimeFilter", kind: "message", T: () => DateTimeFilter },
            { no: 3, name: "operationCodes", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reports.GetUserActonsPdfRequest
 */
export const GetUserActonsPdfRequest = new GetUserActonsPdfRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserActonsPdfResponse$Type extends MessageType<GetUserActonsPdfResponse> {
    constructor() {
        super("fibertest30.reports.GetUserActonsPdfResponse", [
            { no: 1, name: "pdf", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.reports.GetUserActonsPdfResponse
 */
export const GetUserActonsPdfResponse = new GetUserActonsPdfResponse$Type();
/**
 * @generated ServiceType for protobuf service fibertest30.reports.Reports
 */
export const Reports = new ServiceType("fibertest30.reports.Reports", [
    { name: "GetUserActionLines", options: {}, I: GetUserActionLinesRequest, O: GetUserActionLinesResponse },
    { name: "GetUserActonsPdf", options: {}, I: GetUserActonsPdfRequest, O: GetUserActonsPdfResponse }
]);
