// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "rtu_mgmt.proto" (package "fibertest30.rtu_mgmt", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { NetAddress } from "./rtu_tree";
/**
 * @generated from protobuf message fibertest30.rtu_mgmt.TestRtuConnectionRequest
 */
export interface TestRtuConnectionRequest {
    /**
     * not RtuId because it could be new address
     *
     * @generated from protobuf field: fibertest30.rtu_tree.NetAddress netAddress = 1;
     */
    netAddress?: NetAddress;
}
/**
 * @generated from protobuf message fibertest30.rtu_mgmt.TestRtuConnectionResponse
 */
export interface TestRtuConnectionResponse {
    /**
     * @generated from protobuf field: fibertest30.rtu_tree.NetAddress netAddress = 1;
     */
    netAddress?: NetAddress;
    /**
     * @generated from protobuf field: bool isConnectionSuccessful = 2;
     */
    isConnectionSuccessful: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class TestRtuConnectionRequest$Type extends MessageType<TestRtuConnectionRequest> {
    constructor() {
        super("fibertest30.rtu_mgmt.TestRtuConnectionRequest", [
            { no: 1, name: "netAddress", kind: "message", T: () => NetAddress }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.rtu_mgmt.TestRtuConnectionRequest
 */
export const TestRtuConnectionRequest = new TestRtuConnectionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TestRtuConnectionResponse$Type extends MessageType<TestRtuConnectionResponse> {
    constructor() {
        super("fibertest30.rtu_mgmt.TestRtuConnectionResponse", [
            { no: 1, name: "netAddress", kind: "message", T: () => NetAddress },
            { no: 2, name: "isConnectionSuccessful", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message fibertest30.rtu_mgmt.TestRtuConnectionResponse
 */
export const TestRtuConnectionResponse = new TestRtuConnectionResponse$Type();
/**
 * @generated ServiceType for protobuf service fibertest30.rtu_mgmt.RtuMgmt
 */
export const RtuMgmt = new ServiceType("fibertest30.rtu_mgmt.RtuMgmt", [
    { name: "TestRtuConnection", options: {}, I: TestRtuConnectionRequest, O: TestRtuConnectionResponse }
]);
